In [1]:
import numpy as np 
import pandas as pd
import re 
import datetime
import traceback as tb
import sys
import math
import unicodedata
from datetime import time

# Limpieza de datos de CTD 2023

In [13]:
df_ctd = pd.read_excel(r'C:\Users\felipe.abarzua\Desktop\workspace\DATA_AMBIENTALES\Proyecto Seguimiento Ambiental\CTD_2019-2024\5_BD_CTD_SEGUIMIENTO_2023.xlsx')

In [15]:
df_ctd

,Nombre del Proyecto:,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICULTURA EN CHILE Y SU EFECTO EN LOS ECOSISTEMAS DE EMPLAZAMIENTO 2023 -2024,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26
0,Código del Proyecto:,656-160,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Etapa Proyecto:,Objetivo 1. Actividad 2. Muestreos y Análisis ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Jefe Proyecto,Johana Ojeda,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Institución:,Instituto de Fomento Pesquero,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Sectores:,"Estuario de Reloncaví, Seno de Reloncaví, Golf...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6110,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICU...,656-160,13-5-2023,13-5-2023,CTD SeaBird SBE 19plus V 2.5.2 SERIAL NO. 756...,-45.668,-73.299,32,249,253,...,23.1065,NaN,NaN,NaN,X,NaN,32,FIORDO QUITRALCO,13:04:00,1.5
6111,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICU...,656-160,13-5-2023,13-5-2023,CTD SeaBird SBE 19plus V 2.5.2 SERIAL NO. 756...,-45.668,-73.299,32,250,253,...,23.1066,NaN,NaN,NaN,X,NaN,32,FIORDO QUITRALCO,13:04:00,1.5
6112,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICU...,656-160,13-5-2023,13-5-2023,CTD SeaBird SBE 19plus V 2.5.2 SERIAL NO. 756...,-45.668,-73.299,32,251,253,...,23.1066,NaN,NaN,NaN,X,NaN,32,FIORDO QUITRALCO,13:04:00,1.5
6113,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICU...,656-160,13-5-2023,13-5-2023,CTD SeaBird SBE 19plus V 2.5.2 SERIAL NO. 756...,-45.668,-73.299,32,252,253,...,23.1071,NaN,NaN,NaN,X,NaN,32,FIORDO QUITRALCO,13:04:00,1.5
6114,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICU...,656-160,13-5-2023,13-5-2023,CTD SeaBird SBE 19plus V 2.5.2 SERIAL NO. 756...,-45.668,-73.299,32,253,253,...,23.1078,NaN,NaN,NaN,X,NaN,32,FIORDO QUITRALCO,13:04:00,1.5

In [88]:
def limpieza_ctd(df):

    # Creamos una copia del dataset
    df_ctd_copy = df.copy()

    # Eliminamos las filas innecesarias
    df_ctd_copy = df_ctd_copy.iloc[19:  , : ]

    # Dejamos la primera fila como columnas
    df_ctd_copy.columns = df_ctd_copy.iloc[0]

    # Eliminamos la primera fila 
    df_ctd_copy = df_ctd_copy.iloc[1: , :]

    #Reiniciamos los indices
    df_ctd_copy = df_ctd_copy.reset_index(drop = True)

    #Agregamos la columna ID 
    df_ctd_copy.insert(0 , 'ID' , df_ctd_copy.index + 1)

    # Modificamos las columnas de estación ya que existen dos de ellas
    df_ctd_copy.columns.values[8] = 'ESTACION_1'
    df_ctd_copy.columns.values[24] = 'ESTACION_2'

    #Creamos la lista de columnas 
    columnas = df_ctd_copy.columns.to_list()

    #Eliminamos la estacion_2 ya que es innecesaria
    df_ctd_copy.drop(columns=['ESTACION_2'], inplace=True)

    # Renombramos la ESTACION_1 por ESTACION
    df_ctd_copy.columns.values[8] = 'ESTACION'

    #Creamos la lista de columnas 
    columnas = df_ctd_copy.columns.to_list()
    
    #Creamos las columnas fijas y variables
    columnas_fijas = ['ID', 'NOMB_PROY', 'COD_PROY', 'FECHA_INI', 'FECHA_TER', 'EQUIPO', 'LATITUD', 'LONGUITUD', 'ESTACION', 'PROF_EQ', 'PROF_SECT' , 'HORA_INICIO' , 'COD_REG' , 'SECTOR']
    columnas_variables = [ 'TEMPERATUR', 'OXIG_ml/L', 'OXIG_mg/L', 'OXIG_%sat', 'OX_umol/kg','SALINIDAD', 'DENSIDAD', 'CLOROFILA', 'FEOPIGMEN' , 'D_SECCHI']

    
    #Realizamos un melt para convertir las columnas_variables en filas 
    df_ctd_copy = pd.melt(df_ctd_copy , id_vars= columnas_fijas , value_vars= columnas_variables , var_name= 'VARIABLE' , value_name='VALOR')

    #Vamos a reemplazar los valores e HORA_INICIO ya que están mal escritos

    def normalizar_hora_string(hora_str):

            #Normaliza una cadena de tiempo para asegurar que los minutos tengan dos dígitos.
            #Ej: '12:5' se convierte en '12:05'.
            
        if pd.isna(hora_str): # Maneja posibles valores NaN/nulos si los hubiera
            return hora_str

        partes = str(hora_str).split(':')
        if len(partes) != 2:
                # Manejar casos donde el formato no es 'HH:MM' (ej. ya está mal, o es un dato inesperado)
                # Puedes decidir si quieres levantar un error, devolver el original, o un valor específico.
                # Por simplicidad, devolveremos el original si el formato no es el esperado de dos partes.
            return hora_str

        horas = partes[0]
        minutos = partes[1]

        if len(minutos) == 1:
            minutos = '0' + minutos # Añadir el cero delante si es un solo dígito

            return f"{horas}:{minutos}"
        
        #Aplicamos la funcion de hora a la columnas HORA_INICIO
        df_ctd_copy['HORA_INICIO'] = df_ctd_copy['HORA_INICIO'].apply(normalizar_hora_string)

        # Creamos una funcion para convertir la columna de HORA_INICIO a datetime para luego Crear una columna de fecha y hora 
    def convertir_hora(time_value):

        if isinstance(time_value, str): 
                
                # Separamos el ":" del texto y lo convertimos a entero y obtenemos dos variables
                horas, minutos = map(int, time_value.split(':'))
                #Retornamos los valores de Horas y minutos
                return datetime.time(horas, minutos)
        else:
                # En caso que ya es datetime.time se deja como esta
            return time_value


    
    df_ctd_copy['HORA_INICIO'] = df_ctd_copy['HORA_INICIO'].apply(convertir_hora)


    #FECHA INI CONVERTIDA A STRING 
    df_ctd_copy['FECHA_INI_STR'] =  pd.to_datetime(df_ctd_copy['FECHA_INI'] , format = '%d-%m-%Y' , dayfirst= True).dt.strftime("%d/%m/%Y")
    df_ctd_copy['FECHA_TERMINO'] = pd.to_datetime(df_ctd_copy['FECHA_TER'] , format = '%d-%m-%Y' , dayfirst= True).dt.strftime("%d/%m/%Y")

     
        #Creamos una funcion lambda para combinar FECHA_INI con la HORA_INI
    df_ctd_copy['FECHA_INICIO'] = df_ctd_copy.apply(
        lambda row: datetime.datetime.strptime(row['FECHA_INI_STR'], "%d/%m/%Y").replace(
            hour=row['HORA_INICIO'].hour,
            minute=row['HORA_INICIO'].minute,
            second=row['HORA_INICIO'].second
            ),
            axis=1
        )

        # Modificamos el formato de FECHA_INICIO 
    df_ctd_copy['FECHA_INICIO'] = df_ctd_copy['FECHA_INICIO'].dt.strftime("%d/%m/%Y %H:%M:%S")

        # Eliminamos las columnas innecesarias

    df_ctd_copy = df_ctd_copy[['ID', 'NOMB_PROY', 'COD_PROY', 'EQUIPO','LATITUD', 'LONGUITUD', 'ESTACION', 'PROF_EQ', 'PROF_SECT', 'COD_REG', 'SECTOR', 'VARIABLE', 'VALOR',
                                'FECHA_TERMINO', 'FECHA_INICIO']]

        # Cambiamos las variables
    df_ctd_copy['VARIABLE'] = np.where(df_ctd_copy['VARIABLE'] == 'D_SECCHI' , 'DISCO SECCHI' , df_ctd_copy['VARIABLE'] )
    df_ctd_copy['VARIABLE'] = np.where(df_ctd_copy['VARIABLE'] == 'TEMPERATUR' , 'TEMPERATURA' , df_ctd_copy['VARIABLE'] )
        
        # Dejamos las variable en mayuscula
    df_ctd_copy['VARIABLE'] = df_ctd_copy['VARIABLE'].str.upper()

        # Modificamos los valores

    df_ctd_copy['VALOR'] = np.where(df_ctd_copy['VALOR'] == 'sd' , np.nan , df_ctd_copy['VALOR'])

    #Renombramos las columnas 

    df_ctd_copy = df_ctd_copy.rename(columns={'PROF_EQ' : 'PROF_EQU' , 'LONGUITUD' : 'LONGITUD'})

    #Renombramos la columna de NOMB_PROY

    df_ctd_copy['NOMB_PROY'] = 'ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICULTURA EN CHILE Y SU EFECTO EN LOS ECOSISTEMAS DE EMPLAZAMIENTO 2023-2024'
                
    #Renombramos los Equipos

    df_ctd_copy['EQUIPO'] = 'CTD SeaBird SBE 19plus SERIAL NO.7566'


    return df_ctd_copy , columnas

In [89]:
df_ctd_copy , columnas= limpieza_ctd(df_ctd)

In [87]:
df_ctd_copy['EQUIPO'].unique()

array(['CTD SeaBird SBE 19plus V 2.5.2  SERIAL NO. 7566// SBE19plusV2_7566.xmlcon'],
      dtype=object)

In [86]:
print(df_ctd_copy['VALOR'].unique().tolist())

[8.2827, 8.4874, 8.7781, 9.4504, 9.833, 10.3585, 10.8388, 10.9111, 10.9167, 10.9518, 10.8877, 10.8535, 10.8506, 10.8611, 10.8976, 10.915, 10.929, 10.9573, 10.9759, 10.9917, 11.0137, 11.0416, 11.0585, 11.0454, 11.0262, 11.0166, 11.0072, 11.002, 10.9902, 10.9818, 10.9688, 10.9618, 10.9602, 10.9592, 10.9582, 10.958, 10.9579, 10.9587, 10.9585, 10.9581, 10.9566, 10.9558, 10.9555, 10.9556, 10.9552, 10.9547, 10.9544, 10.9542, 10.9536, 10.9533, 10.9532, 10.9527, 10.9525, 10.9524, 10.9522, 10.9515, 10.951, 10.9509, 10.9508, 10.9506, 10.9502, 10.9501, 10.95, 10.9496, 10.9493, 10.9494, 10.9495, 10.9491, 10.9488, 10.9487, 10.9484, 10.9483, 10.948, 10.9478, 10.9481, 10.9482, 10.9486, 10.9499, 10.9511, 10.9519, 10.9523, 10.9529, 10.9535, 10.9537, 10.9539, 10.9541, 10.9545, 10.9548, 10.9551, 10.9554, 10.9561, 10.9567, 10.9571, 10.9575, 10.9589, 10.9595, 10.9597, 10.9601, 10.9604, 10.9605, 10.9609, 10.9606, 8.9275, 8.7787, 8.7468, 8.7584, 8.848, 9.4689, 10.06, 10.3924, 10.577, 10.6522, 10.6897, 10.6996, 10.7072, 10.7094, 10.7177, 10.7299, 10.7391, 10.7682, 10.7848, 10.8024, 10.8376, 10.8528, 10.8486, 10.8452, 10.8556, 10.856, 10.8582, 10.864, 10.8682, 10.8739, 10.8763, 10.8801, 10.8864, 10.8905, 10.8996, 10.8362, 10.9122, 10.9206, 10.8751, 10.9267, 10.9326, 10.9359, 10.9371, 10.9373, 10.939, 10.941, 10.9419, 10.9423, 10.943, 10.9434, 10.9438, 10.9441, 10.9445, 10.9447, 10.9449, 10.945, 10.9452, 10.9455, 10.9456, 10.9458, 10.9461, 10.9463, 10.9464, 10.9466, 10.9468, 10.947, 10.9477, 10.9489, 10.9492, 10.9504, 10.9512, 10.9517, 10.9521, 10.953, 10.956, 10.9574, 10.9599, 10.961, 10.9619, 10.9628, 10.9636, 10.9645, 10.9653, 10.966, 10.9667, 10.9673, 10.968, 10.9686, 10.9693, 10.9699, 10.9705, 10.9711, 10.9717, 10.9724, 10.9731, 10.974, 10.975, 10.976, 10.9771, 10.9782, 10.9794, 10.9806, 10.983, 10.9841, 10.9853, 10.9865, 10.9874, 10.9883, 10.9892, 10.99, 10.9908, 10.9915, 10.9921, 10.9855, 11.0083, 11.0088, 11.0092, 11.0096, 11.01, 11.0105, 11.0109, 11.0114, 11.0713, 11.0417, 11.0415, 11.0414, 11.0413, 11.0411, 11.0409, 11.0408, 11.0406, 11.0404, 11.0402, 11.04, 11.0398, 11.0396, 11.0393, 11.0391, 11.0389, 11.0386, 11.0383, 11.038, 11.0378, 11.0375, 11.0372, 8.6417, 8.7893, 9.0228, 9.6895, 10.4864, 10.8402, 10.9217, 10.9087, 10.8667, 10.8507, 10.8447, 10.8463, 10.8482, 10.8576, 10.8689, 10.8856, 10.9017, 10.9182, 10.9213, 10.927, 10.9331, 10.9387, 10.9439, 10.9617, 10.9627, 10.9624, 10.9568, 10.9507, 10.9498, 10.9497, 10.949, 10.9485, 10.9475, 10.9474, 10.9469, 10.9505, 10.9516, 10.9503, 10.9526, 10.9543, 10.9608, 10.9621, 10.9634, 10.9646, 10.9664, 10.9681, 10.9716, 10.9786, 10.9808, 10.9825, 10.9837, 10.9846, 10.9854, 10.9859, 10.9864, 10.9862, 10.9866, 10.9872, 10.9878, 10.9885, 10.9918, 10.9923, 10.9939, 10.995, 10.9949, 10.9955, 10.9967, 10.9974, 10.9992, 11.0007, 11.0001, 10.9996, 10.9993, 10.9994, 10.9995, 10.9997, 11.0002, 10.9999, 10.9987, 10.9985, 10.9986, 10.9988, 10.9989, 10.9998, 11.0006, 11.0017, 11.0027, 11.0042, 11.0064, 11.007, 11.0077, 11.0086, 11.009, 11.0133, 11.0186, 11.0199, 11.0205, 11.0216, 11.0221, 11.0225, 11.0227, 11.0232, 11.0237, 11.0246, 11.0253, 11.0258, 11.0267, 11.0275, 11.0283, 11.0294, 11.0307, 11.0318, 11.033, 11.0344, 11.0349, 11.0352, 11.0353, 11.0363, 11.0438, 11.0476, 11.0498, 11.054, 11.0569, 11.06, 11.0623, 11.0646, 11.0656, 11.0665, 11.0668, 11.0672, 11.0677, 11.0687, 11.0699, 11.0703, 11.0707, 11.0712, 11.0714, 11.0715, 11.0717, 11.0722, 11.0727, 11.0728, 11.073, 11.0734, 11.0739, 11.0741, 11.0744, 11.0747, 11.0748, 11.0753, 11.0762, 11.077, 11.0783, 11.0793, 11.0799, 11.0802, 11.081, 11.0813, 9.8075, 10.5459, 10.7831, 10.7956, 10.8201, 10.8181, 10.8424, 10.7991, 10.8067, 10.8135, 10.8696, 10.9002, 10.9063, 10.9225, 10.9406, 10.9402, 10.9593, 10.9596, 10.96, 10.9682, 10.9656, 10.9576, 10.9583, 10.9577, 10.9728, 10.9559, 10.9666, 10.9733, 10.9755, 10.977, 10.9788, 10.9812, 10.986, 11.0089, 11.0081, 11.0055, 10.9959, 10.9809, 10.9633, 10.9578, 10.957, 10.9565, 10.9553, 10.9391, 10.9401, 10.9435, 10.9446, 10.9454, 10.9538, 10.9586, 10.9626, 10.9648, 10.9669, 10.9743, 10.9773, 10.98, 10.9822, 10.9839, 10.9876, 10.9886, 10.9894, 10.9901, 10.9947, 10.9972, 10.9984, 10.9991, 11.0004, 11.0019, 11.003, 11.0036, 11.0041, 11.0052, 11.0065, 11.0101, 11.0128, 11.0219, 11.0382, 11.0446, 11.0468, 11.0478, 11.0485, 11.0494, 11.0515, 11.0543, 11.0573, 11.0599, 11.0615, 11.0628, 11.0638, 11.0655, 11.0686, 11.075, 11.0771, 11.0789, 11.0811, 11.0839, 11.0855, 11.0863, 11.0869, 11.0875, 11.0881, 11.0887, 11.0896, 11.0909, 11.0923, 11.0942, 11.0961, 11.0975, 11.0997, 11.1014, 11.101, 11.0993, 11.0979, 11.0992, 11.0989, 11.098, 11.0973, 11.0951, 11.0931, 11.0921, 11.0898, 11.0882, 11.0846, 11.0838, 11.0828, 11.0784, 11.0746, 11.0729, 11.067, 11.065, 11.0633, 11.0616, 11.0606, 11.0584, 11.0556, 11.0532, 11.0496, 11.0471, 11.044, 11.0421, 11.0407, 11.0397, 11.036, 11.0346, 11.0341, 11.0335, 11.0321, 11.0303, 11.028, 11.0268, 11.026, 11.0251, 11.0244, 11.0202, 11.0192, 11.0189, 11.0188, 11.0177, 11.0162, 11.0163, 11.0159, 11.0139, 10.086, 10.0864, 10.0906, 10.1007, 10.119, 10.1517, 10.2038, 10.3323, 10.4924, 10.5985, 10.6834, 10.7367, 10.7413, 10.7446, 10.7487, 10.7546, 10.7592, 10.7614, 10.7645, 10.7687, 10.7746, 10.7804, 10.7821, 10.7823, 10.7825, 10.7843, 10.7861, 10.7868, 10.7871, 10.79, 10.8037, 10.8168, 10.8252, 10.8324, 10.8377, 10.8488, 10.8589, 10.863, 10.8659, 10.8698, 10.8729, 10.8745, 10.8757, 10.8766, 10.8779, 10.8833, 10.895, 10.9108, 10.9199, 10.9215, 10.9234, 10.925, 10.9289, 10.9594, 10.9616, 10.97, 10.9832, 10.9844, 10.9861, 10.9903, 10.993, 10.9953, 10.9978, 10.999, 11.0008, 11.0075, 11.0123, 11.013, 11.0226, 11.0286, 11.032, 11.0464, 11.0507, 11.0533, 11.0538, 11.0539, 11.053, 11.0529, 11.0523, 11.0528, 11.0524, 11.0522, 11.0506, 11.0552, 11.0582, 11.059, 11.0593, 11.0581, 11.0554, 11.0561, 11.0645, 11.0689, 11.0755, 11.0765, 11.0775, 11.0788, 11.0803, 11.0821, 11.0837, 11.0859, 11.0891, 11.0929, 11.0948, 11.1111, 11.1173, 11.1163, 11.1148, 11.1146, 11.1144, 11.1171, 11.1185, 11.1191, 11.1197, 11.1199, 11.1198, 11.12, 11.1196, 11.1194, 11.1195, 11.1201, 11.1202, 11.1204, 11.1206, 11.1207, 11.1208, 11.1205, 11.1203, 11.1212, 11.1214, 11.1215, 11.1216, 11.1218, 11.1219, 11.1223, 11.1227, 11.1229, 11.1232, 11.1235, 11.1237, 11.1239, 11.1243, 11.1251, 11.1255, 11.1256, 11.1252, 11.1254, 11.1257, 11.1258, 11.1259, 11.1262, 11.1265, 11.1269, 11.127, 11.1267, 11.1263, 11.1261, 11.1253, 11.1247, 11.1249, 11.1242, 11.1238, 11.1226, 11.123, 11.1234, 11.1231, 11.1233, 11.1224, 11.121, 11.1209, 11.1192, 11.1166, 11.1123, 11.1093, 11.1071, 11.1057, 11.1052, 11.1051, 11.1054, 11.1044, 11.1036, 11.1039, 11.1041, 11.1042, 11.1043, 11.0807, 11.0964, 11.0954, 11.0953, 11.0949, 11.0944, 11.094, 11.0899, 11.0851, 11.0769, 11.0768, 11.0758, 11.0732, 11.0693, 11.0675, 11.0587, 11.0499, 11.0427, 11.0374, 11.0329, 11.0302, 11.0248, 11.0127, 10.9942, 10.9767, 10.9774, 10.9761, 10.9763, 10.9748, 10.9726, 10.9729, 10.9739, 10.9695, 10.9698, 10.9715, 10.9709, 10.9611, 10.9564, 9.5372, 9.8299, 10.2149, 10.4283, 10.4419, 10.4552, 10.4757, 10.5393, 10.6492, 10.8026, 10.9353, 10.8663, 11.0317, 11.0343, 11.0365, 11.0379, 11.0434, 11.0451, 11.0452, 11.0442, 11.0429, 11.042, 11.0481, 11.0551, 11.0544, 11.0565, 11.0583, 11.0603, 11.0614, 11.0634, 11.078, 11.1297, 11.1309, 11.1285, 11.1278, 11.1283, 11.1317, 11.1369, 11.1401, 11.1406, 11.1397, 11.1389, 11.1035, 11.1359, 11.1355, 11.1346, 11.1327, 11.1311, 11.1305, 11.1304, 11.1303, 11.1296, 11.129, 11.1292, 11.1294, 11.1302, 11.1308, 11.1312, 11.1314, 11.1315, 11.132, 11.1322, 11.1325, 11.1341, 11.1351, 11.1356, 11.1361, 11.1368, 11.1372, 11.1374, 11.1379, 11.1383, 11.1384, 11.1385, 11.1381, 11.138, 11.1375, 11.1373, 11.1371, 11.136, 11.1344, 11.1342, 11.1248, 11.1174, 11.113, 11.1081, 11.1026, 11.0978, 11.0965, 11.0958, 11.0939, 11.0932, 11.0918, 11.0893, 11.0886, 11.0866, 11.0847, 11.0842, 11.0834, 11.0825, 11.0822, 11.082, 11.0806, 11.0777, 11.0764, 11.0759, 11.0754, 11.0757, 11.0756, 11.0761, 11.0723, 11.0709, 11.0704, 11.0681, 11.066, 11.064, 11.0653, 11.0652, 11.0323, 11.0625, 11.061, 11.0594, 11.0589, 11.0586, 11.0592, 11.056, 11.0516, 11.0514, 11.0511, 11.0503, 11.0497, 11.0493, 11.0492, 11.0491, 11.049, 11.0475, 11.0477, 11.0487, 11.0484, 11.0479, 11.0472, 11.0474, 11.046, 11.0444, 11.0433, 11.0426, 11.0419, 11.041, 11.0401, 11.0395, 11.0392, 11.039, 11.0357, 11.035, 11.0338, 11.0327, 11.0316, 11.0311, 11.0305, 11.0296, 11.0285, 11.0254, 11.0252, 11.025, 11.0247, 11.0265, 11.027, 11.0271, 11.0207, 11.019, 11.0195, 11.0173, 11.0236, 11.0234, 11.0228, 11.0223, 11.0222, 11.0214, 11.0197, 11.015, 11.0131, 11.011, 11.0091, 11.0066, 11.0057, 11.0029, 11.0025, 10.9979, 10.998, 10.2895, 10.2924, 10.2904, 10.2927, 10.3027, 10.3074, 10.3143, 10.3198, 10.3307, 10.3533, 10.3648, 10.3707, 10.3816, 10.3889, 10.3942, 10.4071, 10.4567, 10.6373, 10.7471, 10.8212, 10.8863, 10.978, 10.9654, 10.9409, 10.9428, 10.9829, 11.0038, 11.0144, 11.0153, 11.005, 10.9889, 10.9777, 10.9677, 10.9546, 10.9407, 10.9317, 10.9143, 10.9109, 10.9116, 10.9164, 10.9227, 10.9292, 10.9334, 10.9398, 10.964, 10.9684, 10.9692, 10.967, 10.9563, 10.9436, 10.9432, 10.942, 10.9417, 10.4069, 10.4068, 10.4065, 10.4054, 10.4049, 10.4045, 10.4046, 10.4043, 10.4048, 10.405, 10.4053, 10.4055, 10.4056, 10.4058, 10.4062, 10.4064, 10.4066, 10.4074, 10.4072, 10.4077, 10.4079, 10.408, 10.4073, 10.4075, 10.4081, 10.4078, 10.4083, 10.4088, 10.4094, 10.409, 10.4095, 10.4082, 10.4092, 10.4097, 10.4098, 10.41, 10.4101, 10.4105, 10.4107, 10.4109, 10.4111, 10.4113, 10.411, 10.4117, 10.4118, 10.4119, 10.4122, 10.4115, 10.412, 10.4123, 10.4124, 10.4126, 10.4127, 10.4128, 10.413, 10.4131, 10.4121, 10.4129, 10.4125, 10.414, 10.4144, 10.4146, 10.4147, 10.4149, 10.4154, 10.4148, 10.4142, 10.4138, 10.4135, 10.4136, 10.4132, 10.4167, 10.4205, 10.4225, 10.4209, 10.421, 10.4175, 10.4161, 10.4212, 10.4323, 10.4354, 10.4498, 10.4661, 10.4701, 10.47, 10.4706, 10.4743, 10.4753, 10.4758, 10.4784, 10.482, 10.4951, 10.5126, 10.5047, 10.5311, 10.5397, 10.5367, 10.5388, 10.5419, 10.5415, 10.538, 10.5407, 10.5444, 10.5381, 10.5378, 10.5389, 10.5408, 10.5468, 10.5712, 10.5706, 10.58, 10.5858, 10.5843, 10.5879, 10.5967, 10.5945, 10.5953, 10.5983, 10.5986, 10.6014, 10.6029, 10.6026, 10.602, 10.6079, 10.5881, 10.5876, 10.5886, 10.5933, 10.6058, 10.6062, 10.6427, 10.7046, 10.7294, 10.7383, 10.7416, 10.7429, 10.7464, 10.7522, 10.7601, 10.7797, 10.8014, 10.813, 10.8238, 10.8472, 10.8444, 10.8228, 10.8071, 10.8054, 10.8052, 10.804, 10.8011, 10.7984, 10.7982, 10.7977, 10.7967, 10.797, 10.7963, 10.7964, 10.7969, 10.7974, 10.7996, 10.8006, 10.8009, 10.8004, 10.7992, 10.7935, 10.7932, 10.7914, 10.7881, 10.7867, 10.7866, 10.7884, 10.7917, 10.7954, 10.8053, 10.8116, 10.8107, 10.8097, 10.8031, 10.8002, 10.7955, 10.7939, 10.7946, 10.7919, 10.7903, 10.782, 10.7761, 10.7714, 10.7695, 10.7784, 10.7776, 10.7709, 10.7618, 10.7629, 10.7596, 10.7556, 10.7414, 10.728, 10.7193, 10.6768, 10.6464, 10.6416, 10.6389, 10.6391, 10.6405, 10.6379, 10.638, 10.6421, 10.645, 10.6485, 10.6484, 10.6482, 10.627, 10.6279, 10.5959, 10.5774, 10.5616, 10.5466, 10.5427, 10.527, 10.5116, 10.5024, 10.5028, 10.5014, 10.4965, 10.4894, 10.4874, 10.4866, 10.4858, 10.4868, 10.4694, 10.481, 10.4537, 10.4478, 10.4483, 10.4572, 10.4536, 10.4516, 10.4429, 10.4361, 10.4294, 10.4258, 10.4168, 10.4162, 10.4157, 10.4114, 10.4112, 10.4104, 10.4099, 10.4106, 10.4108, 10.406, 10.4059, 10.4061, 10.4076, 10.4063, 10.4087, 10.4086, 10.4091, 10.4089, 10.4085, 10.4051, 10.4067, 10.4057, 10.4052, 10.4156, 10.4272, 10.4366, 10.4342, 10.4336, 10.4352, 10.4372, 10.438, 10.4378, 10.4369, 10.437, 10.4371, 10.4373, 10.4375, 10.4376, 10.4377, 10.4379, 10.4381, 10.4384, 10.4394, 10.4392, 10.4388, 10.4389, 10.4393, 10.4396, 10.4416, 10.4413, 10.4414, 10.4428, 10.442, 10.4399, 10.4404, 10.4401, 10.4408, 10.441, 10.4411, 10.4412, 10.4422, 10.4425, 10.4439, 10.4424, 10.4725, 10.466, 10.464, 10.4686, 10.475, 10.474, 10.4738, 10.4766, 10.4781, 10.4782, 10.4785, 10.4788, 10.4761, 10.4759, 10.4764, 10.4811, 10.4847, 10.4877, 10.4889, 10.4895, 10.4905, 10.4917, 10.4922, 10.4923, 10.492, 10.4927, 10.493, 10.4939, 10.4934, 10.4906, 10.4903, 10.4912, 10.4886, 10.4765, 10.4756, 10.4722, 10.4656, 10.4643, 10.4633, 10.4651, 10.4641, 10.4657, 10.4664, 10.4654, 10.4638, 10.4639, 10.4605, 10.4594, 10.4601, 10.4533, 10.4432, 10.4479, 10.4515, 10.4489, 10.4525, 10.4528, 10.4518, 10.451, 10.4438, 10.4334, 10.433, 10.4238, 10.4201, 10.4166, 10.4151, 10.4133, 10.4134, 10.4139, 10.4137, 10.4103, 10.407, 10.4096, 10.4031, 10.4001, 10.4002, 10.4029, 10.4025, 10.4011, 10.3983, 10.3977, 10.3966, 10.3967, 10.3971, 10.3975, 10.3973, 10.3985, 10.3998, 10.3991, 10.3982, 10.3963, 10.395, 10.3951, 10.3958, 10.398, 10.3987, 10.3993, 10.4, 10.3999, 10.4004, 10.3969, 10.3968, 10.396, 10.3921, 10.3935, 10.3926, 10.3938, 10.3955, 10.3952, 10.3947, 10.3925, 10.3919, 10.3918, 10.3908, 10.3901, 10.3898, 10.3864, 10.3865, 10.3861, 10.3872, 10.3869, 10.3879, 10.3871, 10.3859, 10.3884, 10.3867, 10.3891, 10.3881, 10.3822, 10.3834, 10.1762, 10.1763, 10.1761, 10.1842, 10.1881, 10.189, 10.1937, 10.2103, 10.2598, 10.2774, 10.2809, 10.2796, 10.2778, 10.2729, 10.2686, 10.2611, 10.258, 10.2562, 10.2544, 10.2557, 10.2604, 10.2638, 10.2621, 10.2645, 10.267, 10.2696, 10.2709, 10.2725, 10.2755, 10.2816, 10.2847, 10.2859, 10.2876, 10.2952, 10.3079, 10.3099, 10.3113, 10.3128, 10.3133, 10.3185, 10.3274, 10.3369, 10.3472, 10.3528, 10.3566, 10.3593, 10.3599, 10.36, 10.3588, 10.3557, 10.3561, 10.3562, 10.3558, 10.3564, 10.3582, 10.3578, 10.3573, 10.3586, 10.3602, 10.3628, 10.365, 10.3653, 10.3637, 10.361, 10.3595, 10.359, 10.3574, 10.3563, 10.3567, 10.355, 10.3546, 10.353, 10.3506, 10.3482, 10.3435, 10.3363, 10.3317, 10.3302, 10.3301, 10.333, 10.3322, 10.3305, 10.3261, 10.3246, 10.3245, 10.3248, 10.3247, 10.3249, 10.325, 10.3251, 10.3252, 10.3253, 10.3255, 10.3257, 10.3258, 10.3259, 10.326, 10.3262, 10.3263, 10.3265, 10.3267, 10.3269, 10.327, 10.3272, 10.3273, 10.3275, 10.3277, 10.3279, 10.328, 10.3281, 10.3283, 10.3289, 10.329, 10.3295, 10.331, 10.3312, 10.3306, 10.3315, 10.3314, 10.3319, 10.335, 10.3357, 10.336, 10.3366, 10.3375, 10.3379, 10.338, 10.3384, 10.3389, 10.3393, 10.3395, 10.3396, 10.3397, 10.3398, 10.3399, 10.3401, 10.3402, 10.3404, 10.3406, 10.3407, 9.9991, 10.5219, 10.8956, 10.9792, 10.9843, 10.9203, 10.8754, 10.8202, 10.7745, 10.7499, 10.742, 10.7533, 10.7875, 10.8245, 10.8301, 10.8341, 10.8389, 10.85, 10.8271, 10.7816, 10.7763, 10.7715, 10.7613, 10.749, 10.7463, 10.7449, 10.744, 10.7417, 10.7311, 10.7078, 10.6911, 10.6817, 10.6665, 10.664, 10.6604, 10.6567, 10.6541, 10.6459, 10.644, 10.641, 10.6312, 10.6271, 10.6237, 10.6186, 10.6159, 10.6081, 10.5891, 10.5764, 10.5618, 10.5532, 10.5501, 10.5478, 10.5303, 10.5123, 10.5004, 10.4926, 10.4851, 10.4809, 10.4783, 10.4685, 10.4646, 10.4619, 10.4583, 10.4477, 10.4304, 10.4231, 10.4155, 10.4093, 10.404, 10.4035, 10.4037, 10.4026, 10.4016, 10.4013, 10.3997, 10.3948, 10.3905, 10.3899, 10.3876, 10.3862, 10.3855, 10.3852, 10.3848, 10.3832, 10.38, 10.3776, 10.3761, 10.3716, 10.3639, 10.3612, 10.3608, 10.3607, 10.3601, 10.3587, 10.3559, 10.3517, 10.3505, 10.3489, 10.3479, 10.348, 10.3454, 10.3437, 10.3412, 10.3387, 10.3372, 10.3356, 10.3332, 10.3328, 10.3337, 10.3336, 10.3326, 10.3308, 10.3303, 10.3294, 10.3293, 10.3292, 10.3296, 10.3297, 10.33, 10.3299, 10.3291, 10.3276, 10.3266, 10.3239, 10.3222, 10.3201, 10.3175, 10.3131, 10.3115, 10.3108, 10.3101, 10.3098, 10.3084, 10.3061, 10.3048, 10.304, 10.3029, 10.3028, 10.3032, 10.4841, 10.4855, 10.485, 10.4892, 10.4984, 10.5065, 10.5369, 10.5543, 10.5646, 10.5756, 10.5895, 10.6146, 10.6259, 10.6318, 10.6345, 10.6351, 10.6339, 10.6309, 10.618, 10.5901, 10.579, 10.5697, 10.562, 10.5702, 10.5867, 10.587, 10.5872, 10.588, 10.5947, 10.5984, 10.5915, 10.5864, 10.5844, 10.584, 10.5855, 10.5826, 10.5777, 10.5739, 10.5723, 10.5705, 10.5693, 10.5686, 10.5676, 10.5669, 10.564, 10.5615, 10.561, 10.5607, 10.5605, 10.5593, 10.5577, 10.5558, 10.554, 10.5517, 10.5453, 10.5432, 10.5426, 10.5428, 10.5431, 10.5352, 10.5209, 10.516, 10.5125, 10.5077, 10.5049, 10.5053, 10.5056, 10.5061, 10.5066, 10.5067, 10.5064, 10.5044, 10.5022, 10.5016, 10.5013, 10.4999, 10.4964, 10.4919, 10.4904, 10.4876, 10.4823, 10.4797, 10.4774, 10.4751, 10.4712, 10.4711, 10.4702, 10.4695, 10.4696, 10.4699, 10.4673, 10.4704, 10.465, 10.455, 10.4577, 10.4621, 10.4648, 10.4589, 10.4529, 10.4463, 10.4415, 10.4391, 10.4382, 10.4365, 10.4335, 10.4211, 10.4008, 10.3857, 10.3736, 10.3604, 10.3464, 10.3142, 10.284, 10.2625, 10.2345, 10.2137, 10.2079, 10.2058, 10.2021, 10.1968, 10.1919, 10.1883, 10.1777, 10.1724, 10.1684, 10.1605, 10.1577, 10.155, 10.1508, 10.1473, 10.1456, 10.1454, 10.1439, 10.139, 10.1273, 10.1165, 10.1106, 10.1073, 10.1037, 10.1013, 10.0997, 10.0985, 10.0967, 10.0939, 10.0888, 10.0839, 10.0805, 10.0792, 10.0784, 10.0788, 10.0789, 10.0791, 10.0785, 10.0735, 10.0655, 10.0567, 10.0464, 10.0349, 10.0156, 10.0094, 10.0046, 9.9989, 9.996, 9.9941, 9.9918, 9.9896, 9.987, 9.9842, 9.9834, 9.9833, 9.9826, 9.9822, 9.9824, 9.9818, 9.9795, 9.7303, 10.058, 10.3972, 10.4141, 10.3705, 10.3617, 10.3667, 10.3727, 10.377, 10.3811, 10.3887, 10.3917, 10.3931, 10.3929, 10.3939, 10.4247, 10.427, 10.4287, 10.4305, 10.4333, 10.4356, 10.4443, 10.4467, 10.4524, 10.4688, 10.4947, 10.4954, 10.4956, 10.496, 10.4969, 10.5043, 10.5124, 10.5147, 10.5154, 10.5156, 10.5149, 10.514, 10.5131, 10.5121, 10.5112, 10.51, 10.5073, 10.4863, 10.478, 10.4719, 10.4728, 10.4961, 10.5096, 10.5155, 10.518, 10.5183, 10.5193, 10.5172, 10.5142, 10.5146, 10.5168, 10.5279, 10.5429, 10.5526, 10.5629, 10.5637, 10.5621, 10.5595, 10.5578, 10.5568, 10.553, 10.5521, 10.5549, 10.5617, 10.5681, 10.5789, 10.5927, 10.6128, 10.6177, 10.6214, 10.6252, 10.6272, 10.6316, 10.6325, 10.6341, 10.6348, 10.6364, 10.6426, 10.6449, 10.6488, 10.6516, 10.6542, 10.656, 10.6589, 10.6667, 10.6769, 10.685, 10.6894, 10.6908, 10.6921, 10.6938, 10.6988, 10.7059, 10.7136, 10.7171, 10.7174, 10.7169, 10.7173, 10.7184, 10.7187, 10.7159, 10.7137, 10.7106, 10.6976, 10.6868, 10.6837, 10.6844, 10.6845, 10.6771, 10.6685, 10.6625, 10.6594, 10.6563, 10.6495, 10.6278, 10.6208, 10.6099, 10.5799, 10.3844, 10.3671, 10.3606, 10.3458, 10.3208, 10.2485, 10.1843, 10.1382, 10.0721, 9.9954, 9.963, 9.9458, 9.9263, 9.8928, 9.8346, 9.8118, 9.7909, 9.7605, 9.7463, 9.7399, 9.736, 9.7346, 9.7326, 9.7312, 9.7284, 9.7235, 9.7134, 9.703, 9.6951, 9.6829, 9.6788, 9.6767, 9.6744, 9.6722, 9.6716, 9.6711, 9.6699, 9.6674, 9.6628, 9.6591, 9.6539, 9.6531, 9.6523, 9.6542, 9.6529, 9.6453, 9.6411, 9.6307, 9.6087, 9.5962, 9.5958, 9.594, 9.5929, 9.5915, 9.5911, 10.2289, 10.2287, 10.233, 10.2402, 10.2437, 10.2466, 10.2463, 10.2469, 10.247, 10.2477, 10.246, 10.2455, 10.2459, 10.2554, 10.2594, 10.2575, 10.2694, 10.2745, 10.2759, 10.2841, 10.2908, 10.293, 10.2938, 10.2964, 10.2976, 10.2968, 10.2963, 10.2948, 10.2953, 10.2981, 10.3019, 10.303, 10.3018, 10.3045, 10.3073, 10.3206, 10.3211, 10.322, 10.3235, 10.3417, 10.3442, 10.349, 10.3519, 10.3543, 10.3571, 10.3591, 10.3609, 10.3636, 10.3666, 10.3672, 10.3678, 10.3712, 10.3746, 10.4028, 10.4042, 10.4017, 10.4012, 10.3996, 10.3979, 10.3992, 10.4003, 10.4021, 10.4019, 10.3976, 10.397, 10.3934, 10.3839, 10.3769, 10.3541, 10.352, 10.3512, 10.3497, 10.3673, 10.358, 10.3004, 10.2868, 10.2829, 10.2781, 10.2699, 10.2629, 10.2508, 10.2326, 10.2168, 10.2126, 10.2098, 10.2064, 10.2018, 10.1956, 10.1854, 10.1602, 10.1278, 10.0723, 10.01, 9.9806, 9.976, 9.9732, 9.9699, 9.9677, 9.9641, 9.962, 9.9616, 9.96, 9.9571, 9.95, 9.914, 9.8266, 9.7392, 9.717, 9.654, 9.6055, 9.5573, 9.4834, 9.417, 9.3901, 9.3512, 9.3262, 9.299, 9.2916, 9.2837, 9.2618, 9.2331, 9.2194, 9.2062, 10.3026, 10.3147, 10.4319, 10.55, 10.5899, 10.6132, 10.6965, 10.752, 10.9927, 11.0043, 11.0058, 11.0047, 10.9951, 10.991, 10.9713, 10.9663, 10.9659, 10.9647, 10.9349, 10.905, 10.8902, 10.8603, 10.8354, 10.7973, 10.7863, 10.7803, 10.7708, 10.7805, 10.8292, 10.841, 10.8417, 10.8336, 10.8284, 10.8173, 10.8128, 10.8075, 10.7836, 10.7727, 10.7754, 10.7826, 10.7796, 10.7723, 1

In [90]:
df_ctd_copy.to_csv('output/2023/AMBIENTALES_CTD_2023.csv' , index= False)

# Limpieza de datos Fisico Quimico 2023

In [92]:
df_fisico = pd.read_excel(r'C:\Users\felipe.abarzua\Desktop\workspace\DATA_AMBIENTALES\Proyecto Seguimiento Ambiental\FISICO QUIMICOS_2012-2024\1_BD_FISICOQUIMICO_2023.xlsx')

In [94]:
df_fisico

,Nombre del Proyecto:,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICULTURA EN CHILE Y SU EFECTO EN LOS ECOSISTEMAS DE EMPLAZAMIENTO 2023-2024,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20
0,Etapa Proyecto:,Objetivo 1. Actividad 2. Muestreos y Analisis ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Jefe Proyecto,Gastón Vidal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Institucion:,INSTITUTO DE FOMENTO PESQUERO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Nombre Sector:,"Coquimbo (Tongoy), Seno Reloncaví, Estuario d...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Región:,"Región de Coquimbo, Región de Los Lagos, Regi...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
158,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICU...,Objetivo 1. Actividad 2. Muestreos y Analisis ...,Gastón Vidal,INSTITUTO DE FOMENTO PESQUERO,Campaña_Otoño-Inv_2023.Proy.SeguimientoAmbiental,Natales,9,"51°46'01,6''","72°54'05,0''",7.953333,...,7.266667,0.11547,162.633333,25.971972,26.98233,17.723982,1.961747,2023-08-27 00:00:00,12:32:00,9
159,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICU...,Objetivo 1. Actividad 2. Muestreos y Analisis ...,Gastón Vidal,INSTITUTO DE FOMENTO PESQUERO,Campaña_Otoño-Inv_2023.Proy.SeguimientoAmbiental,Natales,10,"52°03'57,8''","72°56'02,0''",6.566667,...,7.166667,0.152753,291.3,30.677027,86.953482,62.591727,3.1514,2023-08-28 00:00:00,12:30:00,10
160,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICU...,Objetivo 1. Actividad 2. Muestreos y Analisis ...,Gastón Vidal,INSTITUTO DE FOMENTO PESQUERO,Campaña_Otoño-Inv_2023.Proy.SeguimientoAmbiental,Natales,11,"52°11'59,7''","72°57'03,6''",7.396667,...,7.333333,0.057735,185.333333,29.309441,71.829152,28.643757,12.449799,2023-08-27 00:00:00,16:54:00,11
161,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICU...,Objetivo 1. Actividad 2. Muestreos y Analisis ...,Gastón Vidal,INSTITUTO DE FOMENTO PESQUERO,Campaña_Otoño-Inv_2023.Proy.SeguimientoAmbiental,Natales,13,"52°13'10,4''","72°52'26,1''",7.143333,...,7.166667,0.152753,277.466667,4.56545,0.012654,0.021894,2.819486,2023-08-27 00:00:00,17:30:00,13
162,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICU...,Objetivo 1. Actividad 2. Muestreos y Analisis ...,Gastón Vidal,INSTITUTO DE FOMENTO PESQUERO,Campaña_Otoño-Inv_2023.Proy.SeguimientoAmbiental,Natales,14,"52°04'39,3''","72°39'37,6''",7.276667,...,7.366667,0.351188,315.1,39.996125,16.055481,7.706312,9.954389,2023-08-25 00:00:00,18:15:00,14

In [96]:
df_fisico_copy

14,ID,NOMB_PROY,ETAP_PROY,JEFE_PROY,INST_PROY,CAMPAÑA,ZONA,ESTACION,Latitud S,Longitud W,pH,Temperatura (°C),Redox EHNHE (mV),Sulfuros (µM),Materia orgánica total (%),Fecha,Hora Muestreo
0,1,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICU...,Objetivo 1. Actividad 2. Muestreos y Analisis ...,Gastón Vidal,INSTITUTO DE FOMENTO PESQUERO,Campaña_Otoño-Inv_2023.Proy.SeguimientoAmbiental,Estuario,1,"41°26'14,9''","72°17'47,9''",7.023333,11.366667,116.733333,51.551157,4.958564,11/06/2023,09:04:00
1,2,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICU...,Objetivo 1. Actividad 2. Muestreos y Analisis ...,Gastón Vidal,INSTITUTO DE FOMENTO PESQUERO,Campaña_Otoño-Inv_2023.Proy.SeguimientoAmbiental,Estuario,2,"41°28'07,3''","72°18'43,5''",7.263333,11.466667,103.566667,3.088821,3.357422,11/06/2023,08:40:00
2,3,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICU...,Objetivo 1. Actividad 2. Muestreos y Analisis ...,Gastón Vidal,INSTITUTO DE FOMENTO PESQUERO,Campaña_Otoño-Inv_2023.Proy.SeguimientoAmbiental,Estuario,3,"41°29'45,4''","72°18'45,5''",7.326667,11.233333,154.833333,17.46407,2.099861,11/06/2023,09:35:00
3,4,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICU...,Objetivo 1. Actividad 2. Muestreos y Analisis ...,Gastón Vidal,INSTITUTO DE FOMENTO PESQUERO,Campaña_Otoño-Inv_2023.Proy.SeguimientoAmbiental,Estuario,5,"41°30'39,3''","72°17'21,1''",6.926667,11.1,266.533333,56.783292,2.271398,11/06/2023,10:10:00
4,5,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICU...,Objetivo 1. Actividad 2. Muestreos y Analisis ...,Gastón Vidal,INSTITUTO DE FOMENTO PESQUERO,Campaña_Otoño-Inv_2023.Proy.SeguimientoAmbiental,Estuario,6,"41°31'32,6''","72°20'21,4''",7.316667,11.5,167.133333,23.691977,4.9482,10/06/2023,15:40:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
143,144,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICU...,Objetivo 1. Actividad 2. Muestreos y Analisis ...,Gastón Vidal,INSTITUTO DE FOMENTO PESQUERO,Campaña_Otoño-Inv_2023.Proy.SeguimientoAmbiental,Natales,9,"51°46'01,6''","72°54'05,0''",7.953333,7.266667,162.633333,26.98233,1.961747,2023-08-27 00:00:00,12:32:00
144,145,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICU...,Objetivo 1. Actividad 2. Muestreos y Analisis ...,Gastón Vidal,INSTITUTO DE FOMENTO PESQUERO,Campaña_Otoño-Inv_2023.Proy.SeguimientoAmbiental,Natales,10,"52°03'57,8''","72°56'02,0''",6.566667,7.166667,291.3,86.953482,3.1514,2023-08-28 00:00:00,12:30:00
145,146,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICU...,Objetivo 1. Actividad 2. Muestreos y Analisis ...,Gastón Vidal,INSTITUTO DE FOMENTO PESQUERO,Campaña_Otoño-Inv_2023.Proy.SeguimientoAmbiental,Natales,11,"52°11'59,7''","72°57'03,6''",7.396667,7.333333,185.333333,71.829152,12.449799,2023-08-27 00:00:00,16:54:00
146,147,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICU...,Objetivo 1. Actividad 2. Muestreos y Analisis ...,Gastón Vidal,INSTITUTO DE FOMENTO PESQUERO,Campaña_Otoño-Inv_2023.Proy.SeguimientoAmbiental,Natales,13,"52°13'10,4''","72°52'26,1''",7.143333,7.166667,277.466667,0.012654,2.819486,2023-08-27 00:00:00,17:30:00
147,148,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICU...,Objetivo 1. Actividad 2. Muestreos y Analisis ...,Gastón Vidal,INSTITUTO DE FOMENTO PESQUERO,Campaña_Otoño-Inv_2023.Proy.SeguimientoAmbiental,Natales,14,"52°04'39,3''","72°39'37,6''",7.276667,7.366667,315.1,16.055481,9.954389,2023-08-25 00:00:00,18:15:00

In [102]:
def limpieza_fisicoquimico(df):

    # Realizamos una copia del dataset
    df_fisico_copy = df.copy()

    # Eliminamos las filas innecesarias
    df_fisico_copy = df_fisico_copy.iloc[14: , :]

    # Dejamos la primera fila como columnas 
    df_fisico_copy.columns = df_fisico_copy.iloc[0]

    # Eliminamos la primera fila 
    df_fisico_copy = df_fisico_copy.iloc[1: , :]

    #Reiniciamos los indices
    df_fisico_copy = df_fisico_copy.reset_index(drop=True)

    #Seleccionamos las columnas
    df_fisico_copy = df_fisico_copy[['NOMB_PROY', 'ETAP_PROY', 'JEFE_PROY', 'INST_PROY', 'CAMPAÑA', 'ZONA',
       'ESTACION', 'Latitud S                ' , 'Longitud W ', 'pH' , 'Temperatura (°C)' , 'Redox EHNHE (mV)' , 'Sulfuros (µM)   ' , 'Materia orgánica total (%)',
        'Fecha',
       'Hora Muestreo' ]]

    # Agregamos la columna ID

    df_fisico_copy.insert(0 , 'ID' , df_fisico_copy.index + 1 )

    # Creamos una lista de columnas 

    lista_columnas = df_fisico_copy.columns.to_list()


    # Creamos una funcion para eliminar todo el contenido que esta en parentesis (*)

    def es_nan(x):
        return isinstance(x, float) and math.isnan(x)


    def quitar_parentesis_contenido(lista):
    
        resultado = []
        patron = re.compile(r'\([^)]*\)')  # todo lo que esté entre paréntesis (no anida)
        for c in lista:
            if es_nan(c) or c is None:
                resultado.append(c)
            elif isinstance(c, str):
                s = patron.sub('', c)                 # quita ( ... )
                s = re.sub(r'\s{2,}', ' ', s).strip() # colapsa espacios y recorta
                resultado.append(s)
            else:
                resultado.append(c)
        return resultado

    # Aplicamos la funcion para limpiar las columnas 
    lista_columnas = quitar_parentesis_contenido(lista_columnas)

    # Cambiamos las columnas del dataset

    df_fisico_copy.columns = lista_columnas

    # Creamos las columnas fijas y columnas variables

    indices_fijos = [0 , 1 , 2 ,3 ,4 ,5 ,6 ,7 , 8 , 9 ,  15 , 16]

    columnas_fijas = [lista_columnas[i] for i in indices_fijos]

    columnas_variables = [col for i, col in enumerate(lista_columnas) if i not in indices_fijos]

    
    # Ahora realizamos un melt para convertir las columnas variables en filas

    df_fisico_copy = pd.melt(df_fisico_copy , id_vars= columnas_fijas , value_vars= columnas_variables , var_name= 'VARIABLE' , value_name='VALOR' )

    # Convertimos la columna de VARIABLE a mayuscula

    df_fisico_copy['VARIABLE'] = df_fisico_copy['VARIABLE'].str.upper()

    #Corregimos los variables 's/d'
    df_fisico_copy['VALOR'] = np.where(df_fisico_copy['VALOR'] == 'SIN DATO', np.nan , df_fisico_copy['VALOR'] )
    df_fisico_copy['VALOR'] = np.where(df_fisico_copy['VALOR'] == 'sd', np.nan , df_fisico_copy['VALOR'] )
    df_fisico_copy['VALOR'] = np.where(df_fisico_copy['VALOR'] == 's/d', np.nan , df_fisico_copy['VALOR'] )
    
    #Eliminamos las filas con VALOR no nulo 

    df_fisico_copy = df_fisico_copy[df_fisico_copy['VALOR'].notnull()]

    #Reiniciamos los indices    
    df_fisico_copy = df_fisico_copy.reset_index(drop = True)

    # Cambiamos el tipo de dato de la columna Fecha 

    df_fisico_copy['Fecha'] = pd.to_datetime(df_fisico_copy['Fecha'], errors='coerce')

    #Creamos una columna para unir la Fecha y Hora Muestreo

    # Convertimos las Hora_Muestreo que son invalidos a 00:00:00
    df_fisico_copy['Hora Muestreo'] = np.where(df_fisico_copy['Hora Muestreo'] == 'sd' , datetime.time(0,0) , df_fisico_copy['Hora Muestreo'])

    #Creamos la columna llamada FECHA_MUESTREO que combine la fecha y la hora de muestreo
    df_fisico_copy['FECHA_MUESTREO'] = df_fisico_copy['Fecha'].dt.strftime('%d/%m/%Y') + " " + df_fisico_copy['Hora Muestreo'].astype(str)

    # Convertimos las variables 
    df_fisico_copy['VARIABLE'] = np.where(df_fisico_copy['VARIABLE'] == 'MATERIA ORGÁNICA TOTAL' , 'MATERIA ORGANICA' , df_fisico_copy['VARIABLE'])


    def normalizar(s):
            if pd.isna(s):
                return s
            # quitar tildes, bajar a minúsculas y recortar espacios
            s = ''.join(c for c in unicodedata.normalize('NFD', str(s).strip().lower())
                        if unicodedata.category(c) != 'Mn')
            return s

    # Agregamos la columna de COD_REGION
    
    # Diccionario en números romanos
        
    mapa_romano = {
            # Los Lagos (X)
            'reloncavi': 'X',
            'estuario': 'X',
            'calbuco': 'X',
            'maullin': 'X',
            'ancud': 'X',
            'chacao': 'X',
            'butachauques': 'X',
            'chaulinec': 'X',
            'tenaun': 'X',
            'chiloe central': 'X',
            'desertores': 'X',
            'quellon': 'X',
            'hornopiren': 'X',
            'ayacara': 'X',
            'chaiten': 'X',

            # Aysén (XI)
            'guaitecas': 'XI',
            'moraleda': 'XI',
            'puyuhuapi': 'XI',
            'aysen': 'XI',

            # Coquimbo (IV)
            'coquimbo': 'IV',
            'tongoy': 'IV',

            # Atacama (III)
            'atacama': 'III',

            # Magallanes (Natales) – XII
            'natales': 'XII',

            # Biobío (VIII)
            'bio-bio': 'VIII',

            # Los Ríos (XIV)
            'valdivia': 'XIV',
        }

    # Aplicamos la funcion para obtener el COD_REGION
    df_fisico_copy['COD_REGION'] = df_fisico_copy['ZONA'].apply(normalizar).map(mapa_romano)

    #Aplicamos una funcion para eliminar las ' y ° de LATITUD Y LONGITUD 

    df_fisico_copy['Longitud W'] = df_fisico_copy['Longitud W'].str.replace(r"[°'\"]", "", regex=True).str.rstrip().str.replace(',' , '.')
    df_fisico_copy['Latitud S'] = df_fisico_copy['Latitud S'].str.replace(r"[°'\"]", "", regex=True).str.rstrip().str.replace(',' , '.')

    #Renombramos los dataframes

    df_fisico_copy = df_fisico_copy.rename(columns={'Longitud W' : 'LONGITUD' , 'Latitud S' : 'LATITUD' , 'FECHA_MUESTREO' : 'FECHA'})

    #Filtramos las fechas que no sean nulas
    df_fisico_copy = df_fisico_copy[df_fisico_copy['FECHA'].notna()]



    return df_fisico_copy , lista_columnas

In [103]:
df_fisico_copy ,  lista_columnas = limpieza_fisicoquimico(df_fisico)

In [106]:
df_fisico_copy.to_csv('output/2023/AMBIENTALES_FISICOQUIMICO_2023.csv' , index = False)