In [59]:
import numpy as np 
import pandas as pd
import re 
import datetime
import traceback as tb
import sys
import math
import unicodedata
from datetime import time

In [60]:
df_ctd = pd.read_excel(r'C:\Users\felipe.abarzua\Desktop\workspace\DATA_AMBIENTALES\Proyecto Seguimiento Ambiental\CTD_2019-2024\6_BD_CTD_SEGUIMIENTO_2024.xlsx')

In [62]:
df_ctd

,Nombre del Proyecto:,"ESTUDIO DEL DESEMPEÑO AMBIENTAL DE LA ACUICULTURA EN CHILE Y SU EFECTO EN LOS ECOSISTEMAS DE EMPLAZAMIENTO, 2024 -2025",Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29
0,Codigo del Proyecto:,656-171,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Etapa Proyecto:,Objetivo 1. Actividad 2. Muestreos y Análisis ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Jefe Proyecto,Johana Ojeda Palma,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Institución:,Instituto de Fomento Pesquero,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Sectores:,"Estuario de Reloncaví, Seno de Reloncaví, Golf...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6571,ESTUDIO DEL DESEMPEÑO AMBIENTAL DE LA ACUICULT...,656-171,2024-07-25 00:00:00,2024-07-25 00:00:00,CTD SeaBird SBE 19plus SERIAL NO. 01908197//...,-45.668,-73.299,32,247,251,...,NaN,NaN,NaN,NaN,XI,NaN,32,FIORDO QUITRALCO,13:07:00,6
6572,ESTUDIO DEL DESEMPEÑO AMBIENTAL DE LA ACUICULT...,656-171,2024-07-25 00:00:00,2024-07-25 00:00:00,CTD SeaBird SBE 19plus SERIAL NO. 01908197//...,-45.668,-73.299,32,248,251,...,NaN,NaN,NaN,NaN,XI,NaN,32,FIORDO QUITRALCO,13:07:00,6
6573,ESTUDIO DEL DESEMPEÑO AMBIENTAL DE LA ACUICULT...,656-171,2024-07-25 00:00:00,2024-07-25 00:00:00,CTD SeaBird SBE 19plus SERIAL NO. 01908197//...,-45.668,-73.299,32,249,251,...,NaN,NaN,NaN,NaN,XI,NaN,32,FIORDO QUITRALCO,13:07:00,6
6574,ESTUDIO DEL DESEMPEÑO AMBIENTAL DE LA ACUICULT...,656-171,2024-07-25 00:00:00,2024-07-25 00:00:00,CTD SeaBird SBE 19plus SERIAL NO. 01908197//...,-45.668,-73.299,32,250,251,...,11.8915,1.8955,19.188,NaN,XI,NaN,32,FIORDO QUITRALCO,13:07:00,6
6575,ESTUDIO DEL DESEMPEÑO AMBIENTAL DE LA ACUICULT...,656-171,2024-07-25 00:00:00,2024-07-25 00:00:00,CTD SeaBird SBE 19plus SERIAL NO. 01908197//...,-45.668,-73.299,32,251,251,...,NaN,NaN,NaN,NaN,XI,NaN,32,FIORDO QUITRALCO,13:07:00,6

In [ ]:
def limpieza_ctd(df):

    # Creamos una copia del dataset
    df_ctd_copy = df.copy()

    # Eliminamos las filas innecesarias
    df_ctd_copy = df_ctd_copy.iloc[22:  , : ]

    # Dejamos la primera fila como columnas
    df_ctd_copy.columns = df_ctd_copy.iloc[0]

    # Eliminamos la primera fila 
    df_ctd_copy = df_ctd_copy.iloc[1: , :]

    #Reiniciamos los indices
    df_ctd_copy = df_ctd_copy.reset_index(drop = True)

    #Agregamos la columna ID 
    df_ctd_copy.insert(0 , 'ID' , df_ctd_copy.index + 1)

    # Modificamos las columnas de estación ya que existen dos de ellas
    df_ctd_copy.columns.values[8] = 'ESTACION_1'
    df_ctd_copy.columns.values[27] = 'ESTACION_2'

    #Eliminamos la estacion_2 ya que es innecesaria
    df_ctd_copy.drop(columns=['ESTACION_2'], axis=1 , inplace = True)

    # Renombramos la ESTACION_1 por ESTACION
    df_ctd_copy.columns.values[8] = 'ESTACION'

    #Creamos la lista de columnas 
    columnas = df_ctd_copy.columns.to_list()
    

    #Creamos las columnas fijas y variables
    columnas_fijas = ['ID', 'NOMB_PROY', 'COD_PROY', 'FECHA_INI', 'FECHA_TER', 'EQUIPO', 'LATITUD', 'LONGUITUD', 'ESTACION', 'PROF_EQ', 'PROF_SECT' , 'HORA_INICIO' , 'COD_REG' , 'SECTOR']
    columnas_variables = [ 'TEMPERATUR', 'OXIG_ml/L', 'OXIG_mg/L', 'OXIG_%sat', 'OX_umol/kg','SALINIDAD', 'DENSIDAD', 'CLOROFILA', 'FEOPIGMEN' , 'D_SECCHI']

    
    #Realizamos un melt para convertir las columnas_variables en filas 
    df_ctd_copy = pd.melt(df_ctd_copy , id_vars= columnas_fijas , value_vars= columnas_variables , var_name= 'VARIABLE' , value_name='VALOR')


        #Vamos a reemplazar los valores e HORA_INICIO ya que están mal escritos

    def normalizar_hora_string(hora_str):

            #Normaliza una cadena de tiempo para asegurar que los minutos tengan dos dígitos.
            #Ej: '12:5' se convierte en '12:05'.
            
        if pd.isna(hora_str): # Maneja posibles valores NaN/nulos si los hubiera
            return hora_str

        partes = str(hora_str).split(':')
        if len(partes) != 2:
                # Manejar casos donde el formato no es 'HH:MM' (ej. ya está mal, o es un dato inesperado)
                # Puedes decidir si quieres levantar un error, devolver el original, o un valor específico.
                # Por simplicidad, devolveremos el original si el formato no es el esperado de dos partes.
            return hora_str

        horas = partes[0]
        minutos = partes[1]

        if len(minutos) == 1:
            minutos = '0' + minutos # Añadir el cero delante si es un solo dígito

            return f"{horas}:{minutos}"
        
        #Aplicamos la funcion de hora a la columnas HORA_INICIO
        df_ctd_copy['HORA_INICIO'] = df_ctd_copy['HORA_INICIO'].apply(normalizar_hora_string)

        # Creamos una funcion para convertir la columna de HORA_INICIO a datetime para luego Crear una columna de fecha y hora 
    def convertir_hora(time_value):
        if isinstance(time_value, str): 
                # Separamos el ":" del texto y lo convertimos a entero y obtenemos dos variables
                horas, minutos = map(int, time_value.split(':'))
                #Retornamos los valores de Horas y minutos
                return datetime.time(horas, minutos)
        else:
                # En caso que ya es datetime.time se deja como esta
            return time_value


    df_ctd_copy['HORA_INICIO'] = df_ctd_copy['HORA_INICIO'].apply(convertir_hora)


         #Cambiamos los tipos de FECHA_INI y FECHA_FIN a datetime

    df_ctd_copy['FECHA_INI'] = pd.to_datetime(df_ctd_copy['FECHA_INI'])
    df_ctd_copy['FECHA_TER'] = pd.to_datetime(df_ctd_copy['FECHA_TER'])

        #FECHA INI CONVERTIDA A STRING 
    df_ctd_copy['FECHA_INI_STR'] =  df_ctd_copy['FECHA_INI'].dt.strftime("%d/%m/%Y")
    df_ctd_copy['FECHA_TERMINO'] = df_ctd_copy['FECHA_TER'].dt.strftime("%d/%m/%Y")

        
        #Creamos una funcion lambda para combinar FECHA_INI con la HORA_INI
    df_ctd_copy['FECHA_INICIO'] = df_ctd_copy.apply(
        lambda row: datetime.datetime.strptime(row['FECHA_INI_STR'], "%d/%m/%Y").replace(
            hour=row['HORA_INICIO'].hour,
            minute=row['HORA_INICIO'].minute,
            second=row['HORA_INICIO'].second
            ),
            axis=1
        )

    # Modificamos el formato de FECHA_INICIO 
    df_ctd_copy['FECHA_INICIO'] = df_ctd_copy['FECHA_INICIO'].dt.strftime("%d/%m/%Y %H:%M:%S")

    # Eliminamos las columnas innecesarias

    df_ctd_copy = df_ctd_copy[['ID', 'NOMB_PROY', 'COD_PROY', 'EQUIPO','LATITUD', 'LONGUITUD', 'ESTACION', 'PROF_EQ', 'PROF_SECT', 'COD_REG', 'SECTOR', 'VARIABLE', 'VALOR',
                                'FECHA_TERMINO', 'FECHA_INICIO']]

    # Cambiamos las variables
    df_ctd_copy['VARIABLE'] = np.where(df_ctd_copy['VARIABLE'] == 'D_SECCHI' , 'DISCO SECCHI' , df_ctd_copy['VARIABLE'] )
    df_ctd_copy['VARIABLE'] = np.where(df_ctd_copy['VARIABLE'] == 'TEMPERATUR' , 'TEMPERATURA' , df_ctd_copy['VARIABLE'] )
        
     # Dejamos las variable en mayuscula
    df_ctd_copy['VARIABLE'] = df_ctd_copy['VARIABLE'].str.upper()

    #Renombramos las columnas

    df_ctd_copy = df_ctd_copy.rename(columns={'LONGUITUD' : 'LONGITUD' , 'PROF_EQ' : 'PROF_EQU'})

    #Corregimos los NOMB_PROY
    df_ctd_copy['NOMB_PROY'] = 'ESTUDIO DEL DESEMPEÑO AMBIENTAL DE LA ACUICULTURA EN CHILE Y SU EFECTO EN LOS ECOSISTEMAS DE EMPLAZAMIENTO 2024-2025'

    #Renombramos los EQUIPO
    df_ctd_copy['EQUIPO'] = 'CTD SeaBird SBE 19plus SERIAL NO.01908197'

    #Eliminamos los valores incorrectos

    df_ctd_copy['VALOR'] = np.where(df_ctd_copy['VALOR'] == 'sd' , np.nan , df_ctd_copy['VALOR'])


    return df_ctd_copy , columnas

In [85]:
df_ctd_copy , columnas = limpieza_ctd(df_ctd)

In [70]:
df_ctd_copy.columns

Index(['ID', 'NOMB_PROY', 'COD_PROY', 'EQUIPO', 'LATITUD', 'LONGITUD',
       'ESTACION', 'PROF_EQU', 'PROF_SECT', 'COD_REG', 'SECTOR', 'VARIABLE',
       'VALOR', 'FECHA_TERMINO', 'FECHA_INICIO'],
      dtype='object')

In [86]:
print(df_ctd_copy['VALOR'].unique().tolist())

[9.7306, 10.7823, 11.2579, 11.3263, 11.3199, 11.2614, 11.2521, 11.2078, 11.1349, 11.0797, 11.0477, 11.0185, 10.9861, 10.9602, 10.9563, 10.9547, 10.9449, 10.9368, 10.9312, 10.9282, 10.9263, 10.9245, 10.9216, 10.9185, 10.9159, 10.9126, 10.9082, 10.9047, 10.9035, 10.9037, 10.9032, 10.9019, 10.9006, 10.8998, 10.8993, 10.899, 10.8986, 10.8979, 10.8974, 10.8968, 10.8957, 10.8936, 10.8893, 10.8803, 10.8715, 10.8727, 10.881, 10.8877, 10.8987, 10.9003, 10.8992, 10.9005, 10.9026, 10.904, 10.9048, 10.9053, 10.9055, 10.9027, 10.8983, 10.8873, 10.8758, 10.8626, 10.8533, 10.851, 10.8516, 10.8511, 10.8506, 10.8504, 10.85, 10.8513, 10.853, 10.8538, 10.8546, 10.8536, 10.8535, 10.8543, 10.8548, 10.8555, 10.857, 10.8584, 10.8595, 10.8607, 10.8619, 10.8632, 10.8634, 10.8638, 10.8643, 10.8651, 10.8664, 10.8675, 10.8684, 10.8693, 10.8709, 10.8728, 10.874, 10.875, 10.876, 10.8772, 10.8797, 10.8836, 10.8869, 10.8887, 10.8895, 10.8902, 10.8907, 10.8914, 10.892, 10.8919, 10.8918, 10.8924, 10.893, 10.0576, 10.7784, 10.8381, 10.7983, 10.7778, 10.7852, 10.7968, 10.8081, 10.8317, 10.8615, 10.8834, 10.9178, 10.9484, 10.9523, 10.9522, 10.9527, 10.9612, 10.9667, 10.9635, 10.9596, 10.9578, 10.9566, 10.9557, 10.9599, 10.9646, 10.9521, 10.9418, 10.9344, 10.9267, 10.9225, 10.9198, 10.9181, 10.9155, 10.9109, 10.9068, 10.9039, 10.9033, 10.9046, 10.8991, 10.8931, 10.8911, 10.8894, 10.8854, 10.8848, 10.885, 10.8859, 10.8864, 10.8856, 10.8841, 10.8833, 10.8837, 10.8839, 10.8842, 10.8934, 10.909, 10.915, 10.9193, 10.9205, 10.9212, 10.9223, 10.9239, 10.9261, 10.9275, 10.9278, 10.9285, 10.9292, 10.9293, 10.9289, 10.9284, 10.928, 10.9276, 10.9272, 10.9271, 10.9274, 10.9291, 10.9296, 10.9295, 10.9288, 10.927, 10.9294, 10.9287, 10.9315, 10.9342, 10.9341, 10.932, 10.9265, 10.9247, 10.9255, 10.925, 10.9246, 10.9162, 10.9118, 10.9083, 10.9088, 10.9094, 10.9099, 10.9105, 10.9108, 10.9116, 10.9136, 10.916, 10.917, 10.9173, 10.9176, 10.9177, 10.9179, 10.918, 10.9189, 10.9215, 10.9221, 10.9257, 10.9264, 10.9279, 10.9313, 10.9324, 10.9331, 10.9351, 10.9381, 10.9391, 10.9403, 10.9411, 10.9419, 10.9427, 10.9437, 10.9445, 10.9451, 10.9457, 10.9464, 10.9467, 10.947, 10.9474, 10.9479, 10.9489, 10.951, 10.9549, 10.9587, 10.9619, 10.9655, 10.9685, 10.971, 10.9728, 10.9741, 10.9748, 10.9754, 10.9763, 10.9789, 10.9837, 10.9888, 10.9939, 10.998, 11.0002, 11.0011, 11.0021, 11.0037, 11.0064, 11.0079, 11.0092, 11.0108, 11.0129, 11.014, 11.0145, 11.0154, 11.0167, 11.0199, 11.0223, 11.0254, 10.2753, 10.276, 10.2791, 10.2792, 10.2779, 10.2831, 10.2961, 10.3056, 10.3166, 10.3518, 10.405, 10.4337, 10.4598, 10.4933, 10.5517, 10.632, 10.7223, 10.8071, 10.8719, 10.9086, 10.9352, 10.9407, 10.9469, 10.9505, 10.9539, 10.9569, 10.9515, 10.9458, 10.9432, 10.9417, 10.9361, 10.9338, 10.9314, 10.929, 10.9362, 10.9478, 10.9603, 10.9824, 10.9969, 11.0097, 11.024, 11.0422, 11.0617, 11.0726, 11.0654, 11.0412, 11.0057, 10.9657, 10.9307, 10.9119, 10.9049, 10.9025, 10.902, 10.9021, 10.9029, 10.9056, 10.9089, 10.9127, 10.9133, 10.9142, 10.9186, 10.9235, 10.9253, 10.9277, 10.9383, 10.9429, 10.9544, 10.9583, 10.9609, 10.9637, 10.9676, 10.9717, 10.9761, 10.9793, 10.982, 10.9853, 10.9891, 10.9915, 10.9936, 10.9958, 10.9984, 11.0013, 11.0044, 11.0063, 11.0075, 11.0083, 11.0085, 11.008, 11.0068, 11.0055, 11.0048, 11.0058, 11.0056, 11.0066, 11.0091, 11.0116, 11.0157, 11.0152, 11.0179, 11.0209, 11.0203, 11.0169, 11.015, 11.0138, 11.0117, 11.0114, 11.0101, 11.0146, 11.0183, 11.0295, 11.0328, 11.0338, 11.0387, 11.0455, 11.0538, 11.063, 11.0677, 11.0702, 11.0712, 11.0717, 11.073, 11.0758, 11.0832, 11.0956, 11.1051, 11.1092, 11.1117, 11.1155, 11.1185, 11.121, 11.1231, 11.1248, 11.1263, 11.1283, 11.1327, 11.1394, 11.1457, 11.1524, 11.1601, 11.1683, 11.1769, 11.1846, 11.1902, 11.1949, 11.2001, 11.2045, 11.2067, 11.209, 11.2118, 11.2139, 11.2153, 11.2162, 11.2178, 11.2198, 11.2211, 11.221, 11.219, 11.2136, 11.2083, 11.2058, 11.2063, 11.2103, 11.216, 11.2145, 11.2059, 11.2089, 11.2112, 11.214, 11.218, 11.2219, 11.2239, 11.224, 11.2268, 11.2368, 11.2466, 11.2548, 11.2627, 11.2671, 11.2704, 11.2691, 11.2642, 11.2608, 11.262, 11.2645, 11.2658, 11.2662, 11.2666, 11.2674, 11.2695, 11.273, 11.2778, 11.2837, 11.2881, 11.2918, 11.2986, 11.3062, 11.3102, 11.3129, 11.3184, 11.3221, 11.3241, 11.3268, 11.3287, 11.3291, 11.3292, 11.3298, 11.331, 11.3344, 11.3393, 11.3431, 11.345, 11.3461, 11.3471, 11.348, 11.3494, 11.3511, 11.3528, 11.3549, 11.3572, 11.359, 11.3601, 11.361, 11.3619, 11.3628, 11.363, 11.3632, 11.3635, 11.3614, 11.3577, 11.3554, 11.3566, 11.3609, 11.364, 10.0989, 10.1712, 10.3315, 10.4551, 10.5481, 10.6074, 10.6689, 10.7655, 10.9015, 10.9734, 11.0001, 11.005, 11.0317, 11.0389, 11.0427, 11.05, 11.0733, 11.0933, 11.1056, 11.1142, 11.12, 11.127, 11.1347, 11.1358, 11.1369, 11.1403, 11.1426, 11.1397, 11.1324, 11.1239, 11.1203, 11.1208, 11.1226, 11.1225, 11.1152, 11.0965, 11.0783, 11.0701, 11.0663, 11.0697, 11.0841, 11.1088, 11.1354, 11.1533, 11.1608, 11.1653, 11.1666, 11.1617, 11.154, 11.1489, 11.1434, 11.1314, 11.1149, 11.1071, 11.1031, 11.1023, 11.1034, 11.1024, 11.0993, 11.1004, 11.1066, 11.108, 11.1065, 11.1054, 11.106, 11.1017, 11.0958, 11.0952, 11.0981, 11.1022, 11.1091, 11.1134, 11.1175, 11.1276, 11.1433, 11.1565, 11.1688, 11.1758, 11.1811, 11.1874, 11.1957, 11.2022, 11.2061, 11.2096, 11.21, 11.2128, 11.2238, 11.2407, 11.2455, 11.245, 11.2443, 11.2444, 11.2473, 11.251, 11.2542, 11.2568, 11.2587, 11.2601, 11.2621, 11.2639, 11.265, 11.2663, 11.2726, 11.2845, 11.2904, 11.2932, 11.3022, 11.3014, 11.3027, 11.3038, 11.3044, 11.3048, 11.3049, 11.3065, 11.3073, 11.3086, 11.3085, 11.3139, 11.3302, 11.3472, 11.3497, 11.3478, 11.3476, 11.3483, 11.3488, 11.3509, 11.356, 11.3573, 11.3586, 11.36, 11.3633, 11.3683, 11.3742, 11.386, 11.4009, 11.4075, 11.409, 11.4071, 11.3977, 11.3847, 11.3783, 11.3774, 11.3788, 11.3787, 11.3763, 11.3721, 11.3612, 11.3514, 11.3434, 11.3363, 11.327, 11.3236, 11.3237, 11.322, 11.3202, 11.319, 11.3182, 11.3183, 11.3186, 11.3197, 11.3231, 11.3226, 11.3207, 11.3225, 11.3247, 11.3255, 11.3275, 11.3289, 11.3282, 11.3242, 11.3203, 11.3196, 11.3192, 11.3159, 11.3144, 11.3155, 11.3174, 11.3201, 11.321, 11.3206, 11.3198, 11.3211, 11.3195, 11.32, 11.3252, 11.33, 11.3317, 11.3452, 11.3485, 11.3481, 11.3518, 11.3564, 11.3665, 11.379, 11.3849, 11.3873, 11.3876, 11.3902, 11.391, 10.828, 10.6893, 10.7319, 10.7991, 10.867, 10.9209, 10.9485, 10.9592, 10.9614, 10.9581, 10.9584, 10.9611, 10.9649, 10.9669, 10.9671, 10.9736, 10.9755, 10.9757, 10.9808, 10.9858, 10.9894, 11.0051, 11.0283, 11.0598, 11.0943, 11.1222, 11.1363, 11.1488, 11.1649, 11.1796, 11.1864, 11.2357, 11.2906, 11.3454, 11.3533, 11.3605, 11.3751, 11.4106, 11.436, 11.4503, 11.4597, 11.4638, 11.4661, 11.4683, 11.4696, 11.4702, 11.4711, 11.4728, 11.4745, 11.4756, 11.476, 11.4761, 11.4765, 11.4769, 11.4777, 11.4785, 11.4792, 11.4797, 11.4801, 11.4809, 11.4825, 11.4839, 11.485, 11.4856, 11.4857, 11.4862, 11.4871, 11.4879, 11.4888, 11.4899, 11.491, 11.4931, 11.4952, 11.4964, 11.4945, 11.493, 11.4893, 11.4876, 11.4905, 11.4934, 11.4962, 11.4987, 11.4995, 11.4993, 11.4994, 11.4996, 11.4991, 11.4982, 11.498, 11.4981, 11.4985, 11.4986, 11.4989, 11.4984, 11.4999, 11.5016, 11.5029, 11.5035, 11.5034, 11.5032, 11.5022, 11.5026, 11.5037, 11.5036, 11.5015, 11.5011, 11.5008, 11.4988, 11.4972, 11.5013, 11.5027, 11.5023, 11.5007, 11.4997, 11.4967, 11.4925, 11.4881, 11.4852, 11.4859, 11.4846, 11.4821, 11.4767, 11.4717, 11.4666, 11.459, 11.4502, 11.4432, 11.4376, 11.4357, 11.4354, 11.4351, 11.4338, 11.4302, 11.4259, 11.4229, 11.4214, 11.4211, 11.4209, 11.4194, 11.4154, 11.4113, 11.4077, 11.4072, 11.4073, 11.4067, 11.4049, 11.4031, 11.4022, 11.4007, 11.3996, 11.399, 11.3985, 11.3972, 11.3967, 11.3963, 11.3958, 11.3948, 11.3934, 11.3921, 11.3901, 11.3885, 11.3866, 11.3853, 11.3848, 11.3858, 11.3886, 11.3909, 11.3924, 11.3923, 11.3925, 11.3932, 11.3927, 11.393, 11.3946, 11.3993, 11.4017, 11.4038, 11.4061, 11.4088, 11.4098, 11.4114, 11.4118, 11.4119, 11.4117, 11.4108, 11.4037, 11.3968, 11.3919, 11.3869, 11.385, 11.3844, 11.3836, 11.384, 11.3838, 11.3833, 11.3832, 11.382, 11.3803, 11.3781, 11.3743, 11.372, 11.3687, 11.3653, 11.3634, 11.3624, 11.3615, 11.3603, 11.3591, 11.3588, 11.3587, 11.3585, 11.3589, 11.3583, 11.3576, 11.357, 11.3561, 11.3545, 11.353, 11.3522, 11.3515, 11.351, 11.3503, 11.3496, 11.3453, 11.3429, 11.342, 11.3419, 11.3415, 11.3401, 11.3388, 11.3386, 11.339, 11.3379, 11.3358, 11.3346, 11.3335, 11.3323, 11.3313, 11.3301, 11.328, 11.3234, 11.3188, 11.3111, 11.3059, 11.3021, 11.2996, 11.298, 11.294, 11.2899, 11.2915, 10.6028, 10.565, 10.6181, 10.7267, 10.7593, 10.7884, 10.8254, 10.9191, 10.9696, 11.0052, 11.0219, 11.04, 11.0446, 11.0449, 11.0447, 11.0472, 11.0565, 11.0625, 11.0619, 11.0579, 11.0633, 11.0664, 11.0681, 11.0732, 11.0811, 11.0915, 11.1012, 11.1121, 11.1246, 11.1346, 11.1384, 11.139, 11.1393, 11.14, 11.1424, 11.148, 11.1551, 11.1592, 11.1627, 11.1671, 11.1743, 11.1806, 11.1841, 11.1847, 11.1873, 11.1915, 11.1934, 11.1954, 11.1993, 11.2065, 11.2171, 11.2277, 11.2379, 11.2535, 11.2623, 11.268, 11.2774, 11.3212, 11.3325, 11.3364, 11.3389, 11.3412, 11.3502, 11.3539, 11.3579, 11.3606, 11.3638, 11.3648, 11.3445, 11.3439, 11.344, 11.3443, 11.3447, 11.3512, 11.3568, 11.3565, 11.3516, 11.3436, 11.3384, 11.3341, 11.3308, 11.3274, 11.3253, 11.323, 11.3215, 11.3189, 11.3177, 11.3168, 11.3148, 11.3131, 11.311, 11.3035, 11.2947, 11.292, 11.2894, 11.2872, 11.2857, 11.285, 11.2842, 11.2841, 11.2848, 11.2847, 11.2844, 11.284, 11.2839, 11.2836, 11.2826, 11.2806, 11.2769, 11.2724, 11.2689, 11.2668, 11.2656, 11.2646, 11.263, 11.2592, 11.2557, 11.2539, 11.2523, 11.2513, 11.2505, 11.25, 11.2495, 11.2487, 11.2476, 11.2467, 11.2463, 11.2459, 11.2456, 11.2453, 11.2447, 11.2441, 11.2438, 11.243, 11.2386, 11.2376, 11.2373, 11.2364, 11.2359, 11.236, 11.2369, 11.2371, 11.2358, 11.233, 11.2306, 11.2297, 11.2287, 11.2275, 11.2265, 11.225, 11.2237, 11.2232, 11.223, 11.2229, 11.2225, 11.2221, 11.222, 11.2222, 11.2223, 11.2242, 11.2254, 11.226, 11.2259, 11.2258, 11.2245, 11.2233, 11.2226, 11.2214, 11.2208, 11.22, 11.2185, 11.2168, 11.2146, 11.2047, 11.2031, 11.2012, 11.1999, 11.1983, 11.1961, 11.194, 11.1918, 11.1909, 11.1903, 11.1863, 11.1809, 11.1755, 11.1687, 11.1543, 11.146, 11.1409, 11.1387, 11.1365, 11.1321, 11.128, 11.1164, 11.1112, 11.1095, 11.113, 11.122, 11.1293, 11.132, 11.1323, 11.1359, 11.1473, 11.1691, 11.207, 11.2101, 11.2127, 11.2155, 11.2179, 11.2204, 11.2231, 11.2261, 11.2286, 11.2312, 11.2342, 11.235, 11.2325, 11.2142, 11.2151, 11.2157, 11.2164, 11.2174, 11.2195, 11.2248, 11.2266, 11.2269, 11.2228, 11.2209, 11.2206, 11.2193, 11.2158, 11.2159, 11.2165, 11.2161, 11.215, 11.2166, 11.2215, 11.2276, 11.2347, 11.2408, 11.2449, 11.2474, 11.2457, 11.2396, 11.2314, 11.2182, 11.2271, 10.8022, 10.7725, 10.7679, 10.7696, 10.8018, 10.8243, 10.8734, 10.9398, 10.9926, 11.0049, 11.0059, 11.0222, 11.061, 11.0822, 11.0907, 11.0853, 11.0763, 11.0695, 11.0736, 11.0808, 11.0879, 11.093, 11.0953, 11.0968, 11.0969, 11.1026, 11.1122, 11.1127, 11.1098, 11.1143, 11.1207, 11.1374, 11.1419, 11.1463, 11.1485, 11.1515, 11.1552, 11.1555, 11.1545, 11.1553, 11.1591, 11.1603, 11.1594, 11.1584, 11.1579, 11.1574, 11.1547, 11.149, 11.1461, 11.1499, 11.1538, 11.1573, 11.1606, 11.1633, 11.1648, 11.1486, 11.1079, 11.054, 11.0216, 11.0015, 10.974, 10.9492, 10.9092, 10.9079, 10.9137, 10.9157, 10.9166, 10.9169, 10.9171, 10.9168, 10.9175, 10.9202, 10.92, 10.9195, 10.9192, 10.9188, 10.9174, 10.9158, 10.9163, 10.9211, 10.9208, 10.919, 10.9165, 10.9114, 10.9085, 10.9128, 10.924, 10.9268, 10.931, 10.9366, 10.9422, 10.9452, 10.945, 10.9438, 10.943, 10.9431, 10.941, 10.9399, 10.9393, 10.9394, 10.9382, 10.9365, 10.9359, 10.936, 10.9406, 10.9413, 10.9412, 10.9409, 10.9397, 10.9373, 10.9316, 10.9302, 10.93, 10.9204, 10.9172, 10.9154, 10.9076, 10.9017, 10.8997, 10.895, 10.8922, 10.8898, 10.886, 10.8809, 10.8576, 10.8464, 10.842, 10.8391, 10.8364, 10.8297, 10.8246, 10.8215, 10.8198, 10.818, 10.8169, 10.8162, 10.8155, 10.8151, 10.8149, 10.8147, 10.8144, 10.8138, 10.8124, 10.8113, 10.8114, 10.8123, 10.8127, 10.813, 10.8146, 10.8166, 10.8172, 10.8167, 10.8152, 10.821, 10.7596, 10.7625, 10.7683, 10.7694, 10.7724, 10.7755, 10.7768, 10.7773, 10.7776, 10.7785, 10.779, 10.7788, 10.7789, 10.7791, 10.7793, 10.7797, 10.78, 10.7806, 10.7809, 10.7808, 10.781, 10.7811, 10.7812, 10.7813, 10.7817, 10.7818, 10.7819, 10.7816, 10.7814, 10.7831, 10.784, 10.7842, 10.7836, 10.7835, 10.7833, 10.7824, 10.777, 10.7763, 10.7756, 10.7748, 10.7741, 10.7734, 10.773, 10.7729, 10.7728, 10.7731, 10.7721, 10.771, 10.7705, 10.7701, 10.7693, 10.7689, 10.7682, 10.7673, 10.7656, 10.763, 10.7603, 10.7575, 10.753, 10.748, 10.7449, 10.7432, 10.7417, 10.7403, 10.7393, 10.739, 10.7396, 10.7395, 10.74, 10.7409, 10.7419, 10.7423, 10.7421, 10.742, 10.7418, 10.7416, 10.7379, 10.7328, 10.7256, 10.7179, 10.7098, 10.699, 10.6885, 10.6812, 10.6767, 10.6746, 10.6739, 10.6736, 10.6735, 10.6733, 10.6732, 10.6731, 10.6729, 10.6728, 10.6727, 10.6724, 10.6718, 10.6714, 10.671, 10.6708, 10.6707, 10.6698, 10.6687, 10.6686, 10.6683, 10.6682, 10.6681, 10.6679, 10.6677, 10.6676, 10.6678, 10.668, 10.6685, 10.6674, 10.6688, 10.67, 10.6712, 10.6713, 10.6702, 10.6694, 10.6675, 10.6665, 10.6651, 10.6619, 10.6576, 10.6535, 10.6497, 10.647, 10.6459, 10.6454, 10.645, 10.6447, 10.6445, 10.6444, 10.6446, 10.6452, 10.6449, 10.6443, 10.6425, 10.64, 10.6383, 10.6378, 10.6375, 10.6365, 10.6351, 10.6342, 10.634, 10.6337, 10.6335, 10.6338, 10.6346, 10.6352, 10.635, 10.6345, 10.6324, 10.6318, 10.6312, 10.6307, 10.6305, 10.6304, 10.6302, 10.629, 10.6261, 10.6237, 10.6227, 10.6228, 10.6243, 10.6245, 10.6241, 10.6235, 10.6219, 10.6171, 10.6117, 10.6082, 10.6032, 10.5996, 10.5951, 10.588, 10.5829, 10.5819, 10.5826, 10.5837, 10.5855, 10.5873, 10.5899, 10.5918, 10.5917, 10.5913, 10.5915, 10.592, 10.5928, 10.593, 10.5935, 10.5953, 10.5962, 10.5965, 10.5967, 10.5969, 10.5971, 10.5975, 10.5977, 10.5974, 10.6, 10.6192, 10.6175, 10.6226, 10.6453, 10.6594, 10.6649, 10.6692, 10.6979, 10.7609, 10.844, 10.9689, 11.0127, 11.0177, 11.0166, 11.0136, 11.0098, 11.0018, 10.9994, 11.001, 11.0032, 11.0067, 11.0014, 11.003, 11.0022, 10.999, 10.9944, 10.9859, 10.9841, 10.9862, 10.9874, 10.9876, 10.9871, 10.9857, 10.9773, 10.9703, 10.968, 10.9632, 10.9504, 10.9184, 10.8823, 10.8622, 10.8502, 10.8411, 10.8362, 10.8338, 10.8339, 10.837, 10.8388, 10.8417, 10.8453, 10.8467, 10.8469, 10.8473, 10.8526, 10.8572, 10.8564, 10.858, 10.8604, 10.8644, 10.868, 10.8694, 10.8691, 10.866, 10.8647, 10.8637, 10.8627, 10.8617, 10.8599, 10.8567, 10.8544, 10.8532, 10.8527, 10.8519, 10.8514, 10.8491, 10.841, 10.8363, 10.8345, 10.8328, 10.8318, 10.8313, 10.8306, 10.8298, 10.829, 10.8283, 10.8265, 10.8224, 10.8217, 10.8203, 10.8179, 10.8165, 10.8105, 10.808, 10.8073, 10.8072, 10.8066, 10.8049, 10.8023, 10.8, 10.7985, 10.7939, 10.7916, 10.7896, 10.7878, 10.7845, 10.7672, 10.7654, 10.7641, 10.7635, 10.7631, 10.7629, 10.7626, 10.7628, 10.7624, 10.7612, 10.7592, 10.7573, 10.7558, 10.754, 10.7506, 10.7376, 10.7318, 10.7271, 10.7211, 10.7162, 10.7096, 10.6965, 10.6816, 10.673, 10.6671, 10.661, 10.6569, 10.6554, 10.6553, 10.6555, 10.6551, 10.6544, 10.653, 10.6517, 10.6504, 10.6496, 10.6485, 10.6477, 10.6471, 10.6455, 10.6435, 10.641, 10.6373, 10.6299, 10.6278, 10.6269, 10.6264, 10.626, 10.6253, 10.6239, 10.6202, 10.6182, 10.6157, 10.6128, 10.601, 10.708, 10.7068, 10.7087, 10.7183, 10.7286, 10.7326, 10.7327, 10.7324, 10.7325, 10.733, 10.7334, 10.7333, 10.7321, 10.7313, 10.7312, 10.7315, 10.7317, 10.7332, 10.734, 10.7347, 10.731, 10.7303, 10.7293, 10.7291, 10.7277, 10.7273, 10.727, 10.7266, 10.7269, 10.7264, 10.7254, 10.7235, 10.7208, 10.7169, 10.7141, 10.7129, 10.7124, 10.712, 10.7118, 10.7119, 10.6961, 10.679, 10.6734, 10.676, 10.6763, 10.675, 10.6741, 10.662, 10.6566, 10.6542, 10.6522, 10.6478, 10.6416, 10.6366, 10.6301, 10.622, 10.6152, 10.6102, 10.6068, 10.6035, 10.6012, 10.6014, 10.6003, 10.5958, 10.5952, 10.595, 10.5948, 10.5947, 10.5946, 10.5949, 10.5943, 10.5936, 10.5893, 10.5887, 10.5871, 10.5847, 10.5802, 10.5777, 10.5761, 10.5748, 10.5716, 10.5663, 10.5618, 10.5568, 10.5533, 10.5521, 10.5498, 10.5458, 10.5425, 10.5393, 10.5343, 10.5272, 10.5205, 10.5161, 10.5134, 10.5113, 10.5083, 10.5053, 10.5024, 10.4984, 10.4949, 10.4939, 10.4943, 10.4948, 10.4938, 10.4912, 10.4833, 10.4699, 10.4603, 10.4548, 10.4501, 10.4442, 10.4397, 10.4378, 10.4356, 10.4327, 10.4305, 10.4289, 10.4281, 10.428, 10.4284, 10.4292, 10.4303, 10.4322, 10.4339, 10.4348, 10.4346, 10.4347, 10.4354, 10.4359, 10.4361, 10.4363, 10.4366, 10.4367, 10.436, 10.4357, 10.4355, 10.4353, 10.4351, 10.4344, 10.4336, 10.4333, 10.4329, 10.4335, 10.4389, 10.4394, 10.439, 10.4386, 10.4385, 10.4384, 10.4393, 10.4396, 10.4399, 10.4401, 10.4405, 10.4409, 10.4412, 10.4416, 10.4418, 10.4413, 10.441, 10.4402, 10.4391, 10.4369, 10.4316, 10.4298, 10.4267, 10.4222, 10.4178, 10.4145, 10.4124, 10.4111, 10.4099, 10.4087, 10.4078, 10.4074, 10.408, 10.4086, 10.409, 10.4089, 10.4084, 10.4077, 10.4085, 10.3267, 10.3258, 10.3261, 10.3263, 10.3265, 10.3271, 10.3274, 10.3278, 10.3283, 10.329, 10.3294, 10.3303, 10.3323, 10.3341, 10.3355, 10.3361, 10.3349, 10.3313, 10.3252, 10.3194, 10.3154, 10.313, 10.3121, 10.3124, 10.3128, 10.3131, 10.3132, 10.3133, 10.3134, 10.3135, 10.3122, 10.3106, 10.309, 10.3077, 10.3067, 10.3059, 10.3053, 10.3048, 10.3046, 10.3043, 10.3038, 10.3035, 10.3034, 10.3037, 10.3032, 10.3026, 10.3024, 10.3027, 10.303, 10.3033, 10.304, 10.3041, 10.3028, 10.3004, 10.295, 10.2887, 10.283, 10.278, 10.2729, 10.2691, 10.266, 10.2611, 10.2528, 10.2418, 10.2316, 10.2247, 10.2198, 10.2149, 10.2102, 10.207, 10.2052, 10.2042, 10.2036, 10.203, 10.2023, 10.2012, 10.2007, 10.2008, 10.2004, 10.1998, 10.1997, 10.2002, 10.2006, 10.2021, 10.2029, 10.2033, 10.2027, 10.2016, 10.2001, 10.1999, 10.2, 10.2011, 10.2014, 10.2017, 10.2019, 10.202, 10.2022, 10.2005, 10.1987, 10.1968, 10.1957, 10.1951, 10.1947, 10.1945, 10.1944, 10.1943, 10.1941, 10.1933, 10.1919, 10.1906, 10.1899, 10.1898, 10.19, 10.1896, 10.1903, 10.1908, 10.2918, 10.2936, 10.3099, 10.3304, 10.3429, 10.3698, 10.4165, 10.4377, 10.4553, 10.4663, 10.4694, 10.4645, 10.4593, 10.4573, 10.4531, 10.4431, 10.4067, 10.3828, 10.3741, 10.3626, 10.3484, 10.3371, 10.3157, 10.2726, 10.2495, 10.24, 10.2363, 10.2347, 10.233, 10.2301, 10.2297, 10.2276, 10.2269, 10.2253, 10.2199, 10.2153, 10.2142, 10.2148, 10.219, 10.2252, 10.2298, 10.2335, 10.2369, 10.2393, 10.2403, 10.2404, 10.2395, 10.2378, 10.2357, 10.2341, 10.2329, 10.2309, 10.228, 10.226, 10.225, 10.2236, 10.2218, 10.2205, 10.2192, 10.2177, 10.2166, 10.2158, 10.215, 10.2133, 10.21, 10.2073, 10.2064, 10.2062, 10.206, 10.2059, 10.2061, 10.2056, 10.2047, 10.2038, 10.2034, 10.2035, 10.2037, 10.204, 10.2039, 10.2044, 10.2046, 10.2045, 10.2051, 10.2054, 10.2055, 10.2058, 10.2057, 10.205, 10.2048, 10.2063, 10.2072, 10.2078, 10.2081, 10.2088, 10.2093, 10.2096, 10.2098, 10.2101, 10.2105, 10.2107, 10.2108, 10.2109, 10.2122, 9.6436, 9.6412, 9.6408, 9.6532, 9.6811, 9.6998, 9.7077, 9.7099, 9.7148, 9.7193, 9.7207, 9.721, 9.7176, 9.7167, 9.7161, 9.7158, 9.7156, 9.7155, 9.7154, 9.7152, 9.715, 9.7147, 9.7145, 9.7143, 9.7141, 9.714, 9.7159, 9.7175, 9.7184, 9.7189, 9.7191, 9.7192, 9.7195, 9.7196, 9.7197, 9.7198, 9.7199, 9.7201, 9.7203, 9.7202, 9.7188, 9.719, 9.7194, 9.7205, 9.7217, 9.7227, 9.7233, 9.7238, 9.7243, 9.725, 9.7256, 9.7264, 9.7274, 9.7283, 9.7292, 9.7298, 9.7303, 9.7309, 9.7316, 9.7318, 9.7314, 9.7294, 9.7289, 9.7287, 9.7288, 9.7291, 9.7284, 9.7268, 9.7254, 9.7244, 9.7232, 9.7215, 9.7204, 9.7187, 9.7185, 9.7181, 9.7177, 9.7172, 9.717, 9.7168, 9.7166, 9.7163, 9.716, 9.7151, 9.7146, 9.7144, 9.7149, 9.7153, 9.7157, 9.7135, 9.7127, 9.712, 9.7111, 9.7098, 9.7086, 9.7075, 9.7063, 9.7052, 9.7043, 9.7031, 9.7018, 9.7012, 9.701, 9.7011, 9.7013, 9.7017, 9.7021, 9.7023, 9.7016, 9.6999, 9.6976, 9.6941, 9.688, 9.6819, 9.6782, 9.6767, 9.676, 9.6757, 9.6753, 9.6745, 9.6738, 9.6734, 9.6731, 9.6729, 9.6727, 9.6723, 9.6717, 9.6713, 9.671, 9.6707, 8.061, 8.1515, 8.456, 8.9039, 9.2603, 9.4981, 9.6226, 9.6701, 9.6896, 9.6988, 9.7033, 9.711, 9.7139, 9.713

In [87]:
df_ctd_copy.to_csv('output/2024/AMBIENTALES_CTD_2024.csv' , index= False)

# Limpieza de FisicoQuimicos 2024

In [73]:
df_fisico = pd.read_excel(r'C:\Users\felipe.abarzua\Desktop\workspace\DATA_AMBIENTALES\Proyecto Seguimiento Ambiental\FISICO QUIMICOS_2012-2024\1_BD_FISICOQUIMICO_2024.xlsx')

In [ ]:
df_fisico['VALOR'].un

,Nombre del Proyecto:,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICULTURA EN CHILE Y SU EFECTO EN LOS ECOSISTEMAS DE EMPLAZAMIENTO 2024-2025,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20
0,Etapa Proyecto:,Objetivo 1. Actividad 2. Muestreos y Analisis ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Jefe Proyecto,Johana Ojeda,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Institucion:,INSTITUTO DE FOMENTO PESQUERO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Nombre Sector:,"Atacama (Caldera-Bahia Inglesa), Seno Reloncav...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Región:,"Región de Atacama,Región de Los Lagos, Región ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
157,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICU...,Objetivo 1. Actividad 2. Muestreos y Analisis ...,Johana Ojeda,INSTITUTO DE FOMENTO PESQUERO,Campaña_Otoño-Inv_2024.Proy.SeguimientoAmbiental,Natales,9,"51°46'01,6''","72°54'05,0''",7.743333,...,12.5,0.52915,192.133333,21.413158,94.205825,16.523991,3.334888,2024-11-27 00:00:00,15:10:00,9
158,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICU...,Objetivo 1. Actividad 2. Muestreos y Analisis ...,Johana Ojeda,INSTITUTO DE FOMENTO PESQUERO,Campaña_Otoño-Inv_2024.Proy.SeguimientoAmbiental,Natales,10,"52°03'57,8''","72°56'02,0''",7.28,...,8.5,0.141421,195.7,30.211918,34.419753,32.233468,4.886301,2024-11-27 00:00:00,20:20:00,10
159,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICU...,Objetivo 1. Actividad 2. Muestreos y Analisis ...,Johana Ojeda,INSTITUTO DE FOMENTO PESQUERO,Campaña_Otoño-Inv_2024.Proy.SeguimientoAmbiental,Natales,11,"52°11'59,7''","72°57'03,6''",7.79,...,7.766667,0.057735,68,30.63968,109.928276,16.000306,9.156813,2024-11-28 00:00:00,13:30:00,11
160,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICU...,Objetivo 1. Actividad 2. Muestreos y Analisis ...,Johana Ojeda,INSTITUTO DE FOMENTO PESQUERO,Campaña_Otoño-Inv_2024.Proy.SeguimientoAmbiental,Natales,13,"52°13'10,4''","72°52'26,1''",8.093333,...,7.966667,0.11547,-39.8,23.906275,34.289202,4.395151,2.485062,2024-11-28 00:00:00,09:09:00,13
161,ESTUDIO SEGUIMIENTO DESEMPEÑO AMBIENTAL ACUICU...,Objetivo 1. Actividad 2. Muestreos y Analisis ...,Johana Ojeda,INSTITUTO DE FOMENTO PESQUERO,Campaña_Otoño-Inv_2024.Proy.SeguimientoAmbiental,Natales,14,"52°04'39,3''","72°39'37,6''",7.153333,...,9.666667,0.862168,186.166667,19.20217,39.033492,21.727464,3.647264,2024-11-27 00:00:00,10:50,14

In [101]:
def limpieza_fisicoquimico(df):

    # Realizamos una copia del dataset
    df_fisico_copy = df.copy()

    # Eliminamos las filas innecesarias
    df_fisico_copy = df_fisico_copy.iloc[14: , :]

    # Dejamos la primera fila como columnas 
    df_fisico_copy.columns = df_fisico_copy.iloc[0]

    # Eliminamos la primera fila 
    df_fisico_copy = df_fisico_copy.iloc[1: , :]

    #Reiniciamos los indices
    df_fisico_copy = df_fisico_copy.reset_index(drop=True)

    #Seleccionamos las columnas
    df_fisico_copy = df_fisico_copy[['NOMB_PROY', 'ETAP_PROY', 'JEFE_PROY', 'INST_PROY', 'CAMPAÑA', 'ZONA',
       'ESTACION', 'Latitud S                ' , 'Longitud W ', 'pH' , 'Temperatura (°C)' , 'Redox EHNHE (mV)' , 'Sulfuros (µM)   ' , 'Materia orgánica total (%)',
        'Fecha',
       'Hora Muestreo' ]]

    # Agregamos la columna ID

    df_fisico_copy.insert(0 , 'ID' , df_fisico_copy.index + 1 )

    # Creamos una lista de columnas 

    lista_columnas = df_fisico_copy.columns.to_list()


    # Creamos una funcion para eliminar todo el contenido que esta en parentesis (*)

    def es_nan(x):
        return isinstance(x, float) and math.isnan(x)


    def quitar_parentesis_contenido(lista):
    
        resultado = []
        patron = re.compile(r'\([^)]*\)')  # todo lo que esté entre paréntesis (no anida)
        for c in lista:
            if es_nan(c) or c is None:
                resultado.append(c)
            elif isinstance(c, str):
                s = patron.sub('', c)                 # quita ( ... )
                s = re.sub(r'\s{2,}', ' ', s).strip() # colapsa espacios y recorta
                resultado.append(s)
            else:
                resultado.append(c)
        return resultado

    # Aplicamos la funcion para limpiar las columnas 
    lista_columnas = quitar_parentesis_contenido(lista_columnas)

    # Cambiamos las columnas del dataset

    df_fisico_copy.columns = lista_columnas

    # Creamos las columnas fijas y columnas variables

    indices_fijos = [0 , 1 , 2 ,3 ,4 ,5 ,6 ,7 , 8 , 9 ,  15 , 16]

    columnas_fijas = [lista_columnas[i] for i in indices_fijos]

    columnas_variables = [col for i, col in enumerate(lista_columnas) if i not in indices_fijos]

    
    # Ahora realizamos un melt para convertir las columnas variables en filas

    df_fisico_copy = pd.melt(df_fisico_copy , id_vars= columnas_fijas , value_vars= columnas_variables , var_name= 'VARIABLE' , value_name='VALOR' )

    # Convertimos la columna de VARIABLE a mayuscula

    df_fisico_copy['VARIABLE'] = df_fisico_copy['VARIABLE'].str.upper()

    #Corregimos los variables 's/d'
    df_fisico_copy['VALOR'] = np.where(df_fisico_copy['VALOR'] == 'SIN DATO', np.nan , df_fisico_copy['VALOR'] )
    df_fisico_copy['VALOR'] = np.where(df_fisico_copy['VALOR'] == 'sd', np.nan , df_fisico_copy['VALOR'] )
    df_fisico_copy['VALOR'] = np.where(df_fisico_copy['VALOR'] == 's/d', np.nan , df_fisico_copy['VALOR'] )
    
    #Eliminamos las filas con VALOR no nulo 

    df_fisico_copy = df_fisico_copy[df_fisico_copy['VALOR'].notnull()]

    #Reiniciamos los indices    
    df_fisico_copy = df_fisico_copy.reset_index(drop = True)

    # Cambiamos el tipo de dato de la columna Fecha 

    df_fisico_copy['Fecha'] = pd.to_datetime(df_fisico_copy['Fecha'], errors='coerce')

    #Creamos una columna para unir la Fecha y Hora Muestreo

    # Convertimos las Hora_Muestreo que son invalidos a 00:00:00
    df_fisico_copy['Hora Muestreo'] = np.where(df_fisico_copy['Hora Muestreo'] == 'sd' , datetime.time(0,0) , df_fisico_copy['Hora Muestreo'])

    # Convertimos los errores de la Hora Muestreo '14.40' Y '   10:50'

    df_fisico_copy['Hora Muestreo'] = np.where(df_fisico_copy['Hora Muestreo'] == '   10:50' , datetime.time(10,50) , df_fisico_copy['Hora Muestreo'])
    df_fisico_copy['Hora Muestreo'] = np.where(df_fisico_copy['Hora Muestreo'] == '14.40' , datetime.time(14,40) , df_fisico_copy['Hora Muestreo'])
    


    #Creamos la columna llamada FECHA_MUESTREO que combine la fecha y la hora de muestreo
    df_fisico_copy['FECHA_MUESTREO'] = df_fisico_copy['Fecha'].dt.strftime('%d/%m/%Y') + " " + df_fisico_copy['Hora Muestreo'].astype(str)

    # Convertimos las variables 
    df_fisico_copy['VARIABLE'] = np.where(df_fisico_copy['VARIABLE'] == 'MATERIA ORGÁNICA TOTAL' , 'MATERIA ORGANICA' , df_fisico_copy['VARIABLE'])


    def normalizar(s):
            if pd.isna(s):
                return s
            # quitar tildes, bajar a minúsculas y recortar espacios
            s = ''.join(c for c in unicodedata.normalize('NFD', str(s).strip().lower())
                        if unicodedata.category(c) != 'Mn')
            return s

    # Agregamos la columna de COD_REGION
    
    # Diccionario en números romanos
        
    mapa_romano = {
            # Los Lagos (X)
            'reloncavi': 'X',
            'estuario': 'X',
            'calbuco': 'X',
            'maullin': 'X',
            'ancud': 'X',
            'chacao': 'X',
            'butachauques': 'X',
            'chaulinec': 'X',
            'tenaun': 'X',
            'chiloe central': 'X',
            'desertores': 'X',
            'quellon': 'X',
            'hornopiren': 'X',
            'ayacara': 'X',
            'chaiten': 'X',

            # Aysén (XI)
            'guaitecas': 'XI',
            'moraleda': 'XI',
            'puyuhuapi': 'XI',
            'aysen': 'XI',

            # Coquimbo (IV)
            'coquimbo': 'IV',
            'tongoy': 'IV',

            # Atacama (III)
            'atacama': 'III',

            # Magallanes (Natales) – XII
            'natales': 'XII',

            # Biobío (VIII)
            'bio-bio': 'VIII',

            # Los Ríos (XIV)
            'valdivia': 'XIV',
        }

    # Aplicamos la funcion para obtener el COD_REGION
    df_fisico_copy['COD_REGION'] = df_fisico_copy['ZONA'].apply(normalizar).map(mapa_romano)

    #Aplicamos una funcion para eliminar las ' y ° de LATITUD Y LONGITUD 

    df_fisico_copy['Longitud W'] = df_fisico_copy['Longitud W'].str.replace(r"[°'\"]", "", regex=True).str.rstrip().str.replace(',' , '.')
    df_fisico_copy['Latitud S'] = df_fisico_copy['Latitud S'].str.replace(r"[°'\"]", "", regex=True).str.rstrip().str.replace(',' , '.')

    #Renombramos los dataframes

    df_fisico_copy = df_fisico_copy.rename(columns={'Longitud W' : 'LONGITUD' , 'Latitud S' : 'LATITUD'})

  
    return df_fisico_copy , lista_columnas

In [103]:
df_fisico_copy , lista_columnas = limpieza_fisicoquimico(df_fisico)

In [106]:
df_fisico_copy.to_csv('output/2024/AMBIENTALES_FISICOQUIMICO_2024.csv' , index= False)

In [91]:
df_fisico_copy.columns

Index(['ID', 'NOMB_PROY', 'ETAP_PROY', 'JEFE_PROY', 'INST_PROY', 'CAMPAÑA',
       'ZONA', 'ESTACION', 'LATITUD', 'LONGITUD', 'Fecha', 'Hora Muestreo',
       'VARIABLE', 'VALOR', 'FECHA_MUESTREO', 'COD_REGION'],
      dtype='object')

In [105]:
df_fisico_copy['FECHA_MUESTREO'].unique()

array(['20/05/2024 09:35:00', '20/05/2024 09:16:00',
       '19/05/2024 16:20:00', '19/05/2024 15:50:00',
       '19/05/2024 15:00:00', '19/05/2024 15:30:00',
       '19/05/2024 14:15:00', '19/05/2024 11:00:00',
       '19/05/2024 09:45:00', '19/05/2024 09:00:00',
       '21/05/2024 15:20:00', '21/05/2024 16:20:00',
       '22/05/2024 09:00:00', '23/05/2024 08:50:00',
       '18/05/2024 08:55:00', '18/05/2024 10:05:00',
       '18/05/2024 11:00:00', '18/05/2024 12:00:00',
       '18/05/2024 13:55:00', '21/05/2024 14:25:00',
       '23/05/2024 08:20:00', '22/05/2024 16:10:00',
       '23/05/2024 10:20:00', '23/05/2024 11:30:00',
       '22/05/2024 15:30:00', '22/05/2024 12:00:00',
       '22/05/2024 14:30:00', '22/05/2024 14:50:00',
       '24/05/2024 12:00:00', '24/05/2024 11:30:00',
       '24/05/2024 11:40:00', '24/05/2024 11:10:00',
       '25/05/2024 10:45:00', '25/05/2024 11:20:00',
       '25/05/2024 12:40:00', '25/05/2024 10:00:00',
       '25/05/2024 08:45:00', '25/05/2024 08:20:00',
       '24/05/2024 14:10:00', '26/05/2024 10:35:00',
       '26/05/2024 11:15:00', '26/05/2024 09:50:00',
       '25/05/2024 15:15:00', '26/05/2024 14:50:00',
       '26/05/2024 16:55:00', '27/05/2024 08:15:00',
       '27/05/2024 08:45:00', '26/05/2024 15:20:00',
       '27/05/2024 14:45:00', '27/05/2024 13:35:00',
       '27/05/2024 13:00:00', '27/05/2024 10:25:00',
       '27/05/2024 11:00:00', '27/05/2024 11:35:00',
       '29/05/2024 10:45:00', '26/05/2024 12:00:00',
       '19/06/2024 15:30:00', '22/06/2024 09:15:00',
       '22/06/2024 09:50:00', '22/06/2024 10:45:00',
       '01/06/2024 11:05:00', '01/06/2024 12:05:00',
       '01/06/2024 12:35:00', '01/06/2024 10:15:00',
       '01/06/2024 09:30:00', '31/05/2024 15:10:00',
       '31/05/2024 14:35:00', '31/05/2024 14:00:00',
       '31/05/2024 12:50:00', '31/05/2024 12:30:00',
       '31/05/2024 11:45:00', '29/05/2024 13:15:00',
       '14/06/2024 15:25:00', '14/06/2024 14:20:00',
       '14/06/2024 13:45:00', '14/06/2024 17:20:00',
       '15/06/2024 13:15:00', '15/06/2024 14:50:00',
       '15/06/2024 17:15:00', '15/06/2024 16:00:00',
       '19/06/2024 12:10:00', '19/06/2024 13:00:00',
       '16/06/2024 13:30:00', '16/06/2024 14:20:00',
       '23/06/2024 12:00:00', '23/06/2024 11:00:00',
       '05/08/2024 07:21:00', '04/08/2024 16:35:00',
       '14/07/2024 10:50:00', '14/07/2024 10:20:00',
       '14/07/2024 08:30:00', '13/07/2024 16:00:00',
       '13/07/2024 14:35:00', '12/07/2024 09:30:00',
       '12/07/2024 08:45:00', '12/07/2024 10:20:00',
       '12/07/2024 11:10:00', '12/07/2024 14:40:00',
       '16/07/2024 15:05:00', '16/07/2024 14:00:00',
       '16/07/2024 12:30:00', '14/07/2024 14:50:00',
       '14/07/2024 14:00:00', '14/07/2024 12:30:00',
       '14/07/2024 11:40:00', '12/07/2024 13:00:00',
       '04/08/2024 15:10:00', '04/08/2024 11:30:00',
       '02/08/2024 10:45:00', '29/07/2024 15:40:00',
       '01/08/2024 11:50:00', '30/07/2024 15:30:00',
       '30/07/2024 14:50:00', '30/07/2024 12:45:00',
       '30/07/2024 11:14:00', '23/07/2024 08:55:00',
       '23/07/2024 15:45:00', '18/07/2024 17:15:00',
       '18/07/2024 12:00:00', '18/07/2024 09:45:00',
       '26/07/2024 10:45:00', '26/07/2024 14:10:00',
       '28/07/2024 14:15:00', '28/07/2024 00:00:00',
       '17/07/2024 13:50:00', '17/07/2024 12:00:00',
       '17/07/2024 10:28:00', '17/07/2024 08:45:00',
       '29/07/2024 12:10:00', '07/08/2024 13:20:00',
       '07/08/2024 12:30:00', '07/08/2024 12:00:00',
       '07/08/2024 11:35:00', '07/08/2024 11:20:00',
       '07/08/2024 09:30:00', '30/11/2024 09:30:00',
       '30/11/2024 08:30:00', '28/11/2024 17:20:00',
       '27/11/2024 15:10:00', '27/11/2024 20:20:00',
       '28/11/2024 13:30:00', '28/11/2024 09:09:00',
       '27/11/2024 10:50:00'], dtype=object)